### ISSUE TITLE
Tabs 使用数组动态设置Tab打包成小程序默认选中tab没有下划线，切换其他的Tab可以显示下划线

### ISSUE THREAD

**Issue by MarkLogin** [AntmJS/vantui#105]
**BUG描述**

Tabs 使用数组动态设置Tab打包成小程序默认选中tab没有下划线，切换其他的Tab可以显示下划线
**复现步骤**

<Tabs active={0}
            titleActiveColor='#388FFF'
            titleInactiveColor='#666666'
            lineHeight='4px'
            lineWidth='35px'
            color='#388FFF'
            zIndex={0}
            ellipsis={false}>
            {
                props.data.length > 0 && props.data.map((item, index) =>
                    <Tab key={index}
                        title={item.expenseName}
                        titleStyle='font-size: 15px'>
                        {'内容:' + index}
                    </Tab>
                )
            }
        </Tabs>
**期望结果**

默认选中的Tab显示下划线
**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/12522661/144953627-82ee72e0-bc04-49cc-a3ee-fd694f136025.png)

**环境**

"@antmjs/vantui": "^1.2.9"
**附加信息**

**Comment by Banlangenn** [comment]
给个最小 复现

**Comment by MarkLogin** [comment]
import { Tabs, Tab } from '@antmjs/vantui'
import { View, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'

import './index.less'
import { useState } from 'react'
import { useReady } from '@tarojs/runtime'

const ExpenseInfo = (props) => {

    const [tabs, setTabs] = useState(Array())

    useReady(() => {
        Taro.request({ url: 'https://www.tianqiapi.com/free/day?appid=75495355&appsecret=qwdesfs&unescape=1', 'method': 'GET' })
            .then((res) => {
                var tab = new Array()
                tab.push('测试1')
                tab.push('测试2')
                tab.push('测试3')
                tab.push('测试4')
                tab.push('测试5')
                setTabs(tab)
            })
    })

    return (<View>
        <Tabs active={0}
            titleActiveColor='#388FFF'
            titleInactiveColor='#666666'
            lineHeight='4px'
            lineWidth='35px'
            color='#388FFF'
            zIndex={0}
            ellipsis={false}>
            {
                tabs.length > 0 && tabs.map((item, index) =>
                    <Tab key={index}
                        title={item}
                        titleStyle='font-size: 15px'>
                    </Tab>
                )
            }
        </Tabs>
    </View>)
}

export default ExpenseInfo

**Comment by MarkLogin** [comment]
> 给个最小 复现

是

**Comment by Banlangenn** [comment]
收到

**Comment by hisanshao** [comment]
@MarkLogin 1.2.10解决了

**Comment by MarkLogin** [comment]
> @MarkLogin 1.2.10解决了
1.2.10版本中 packages/vantui/src/tabs/index.tsx  缺少taro 引用报错了。import Taro from '@tarojs/taro'

**Comment by hisanshao** [comment]
@MarkLogin 马上修复

**Comment by hisanshao** [comment]
@MarkLogin 1.3.1
