### ISSUE TITLE
自定义下拉菜单，DropdownItem 的 title 属性无法显示。vantUI正常

### ISSUE THREAD

**Issue by LiQing-He** [AntmJS/vantui#118]
**BUG描述**
自定义下拉菜单，title属性无法显示

**复现步骤**

**期望结果**
正常显示title

**实际结果**

**截图**
![自定义菜单bug](https://user-images.githubusercontent.com/75653843/145917688-35563a8d-c70e-4f18-965c-2776f446a83c.jpg)

**环境**
版本1.4.1。微信小程序

**附加信息**

**Comment by hisanshao** [comment]
1.4.2已修复
