### ISSUE TITLE
希望TreeSelect组件支持多级树形结构选择，目前仅两级

### ISSUE THREAD

**Issue by LiQing-He** [AntmJS/vantui#119]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
 TreeSelect 目前仅支持两级选择。Picker选择器联动不支持多选。希望有多级树形结构选择组件

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by zuolung** [comment]
手机屏幕太小，没有办法去展示更多的层级
