### ISSUE TITLE
无法启动钉钉小程序

### ISSUE THREAD

**Issue by valkia** [AntmJS/vantui#121]
**BUG描述**
启动钉钉小程序命令，在开发者工具报错，微信和飞书小程序可以正常运行。

**复现步骤**
1.拉取AntmJS/vantui demo代码运行钉钉小程序报错
2.拉取taro模版代码启动钉钉小程序正常，引入AntmJS/vantui组件后报错
都是提示TypeError: Object is not a function
**期望结果**
可以运行

**实际结果**
无法运行

**截图**
![微信截图_20211215113943](https://user-images.githubusercontent.com/24906472/146118947-3d11ccb5-b66a-430e-b009-fb4a16419980.png)

**环境**
windows

**附加信息**

**Comment by hisanshao** [comment]
参考https://github.com/AntmJS/temptaro/blob/main/config/webpack/globalLoader.js 把alipay改成dd

**Comment by valkia** [comment]
> 参考https://github.com/AntmJS/temptaro/blob/main/config/webpack/globalLoader.js 把alipay改成dd

![微信截图_20211215120115](https://user-images.githubusercontent.com/24906472/146120948-870d51c7-3534-4ba9-86a9-a513908d1dd5.png)
demo代码中有这一块，但是依然报TypeError: Object is not a function

**Comment by hisanshao** [comment]
用的是vantui/packages/vantui-demo这个工程来跑的吗

**Comment by valkia** [comment]
> 用的是vantui/packages/vantui-demo这个工程来跑的吗

是的

**Comment by hisanshao** [comment]
![image](https://user-images.githubusercontent.com/26359618/146133596-f27b2a99-908b-4631-bc7c-96eda9b1aed0.png)
可以打开的啊，我们测试过钉钉的呢 你截图的错大概率是编译导致的。你看下有没有改什么配置过

**Comment by hisanshao** [comment]
你是不是配置了useBuiltIns: 'usage'。截图的错误是Taro本身的错，你可以拉一个新的工程先不要装vantui组件跑一下。如果你需要处理polyfill建议你直接拷贝vantui-demo的config目录和babel.config.js。这个也是我们现在在用的配置，是可以正常运行的。

**Comment by valkia** [comment]
> 你是不是配置了useBuiltIns: 'usage'。截图的错误是Taro本身的错，你可以拉一个新的工程先不要装vantui组件跑一下。如果你需要处理polyfill建议你直接拷贝vantui-demo的config目录和babel.config.js。这个也是我们现在在用的配置，是可以正常运行的。

vantui-demo 拉下来就是useBuiltIns: 'usage'了。
代码没改过，都是拉下拉直接运行的。

**Comment by hisanshao** [comment]
![image](https://user-images.githubusercontent.com/26359618/146528929-91714855-60be-430e-8a91-94930b4c8743.png)
是按照这个执行的吗

**Comment by valkia** [comment]
> ![image](https://user-images.githubusercontent.com/26359618/146528929-91714855-60be-430e-8a91-94930b4c8743.png) 是按照这个执行的吗

没有跑yarn那段。是这个原因吗，我看微信和飞书都是正常运行就是钉钉不行

**Comment by hisanshao** [comment]
已修复，可以重新拉下temptaro的仓库代码
