### ISSUE TITLE
does not contain an export named 'DropdownItem' 报错

### ISSUE THREAD

**Issue by skyliwq** [AntmJS/vantui#122]
React Taro 下使用 DropdownItem 报错 does not contain an export named 'DropdownItem'
"@tarojs/react": "3.3.16",

import {Icon, NavBar, DropdownItem, DropdownMenu} from '@antmjs/vantui';

  <DropdownMenu>
          <DropdownItem value={0} options={option1}/>
          <DropdownItem value={'a'} options={option2}/>
        </DropdownMenu>

**Comment by hisanshao** [comment]
更新版本试试，这个应该没问题的，最近有运行过的

**Comment by skyliwq** [comment]
DropdownItem 这样引入无效 import {Icon, NavBar, DropdownItem, DropdownMenu} from '@antmjs/vantui';
这样可以 import DropdownItem from '@antmjs/vantui/es/dropdown-item';

 DropdownMenu 下面的内容间距这么大吗？ 在哪里可以更改？

![image](https://tunger.oss-cn-beijing.aliyuncs.com/%E6%88%AA%E5%B1%8F2021-12-15%2016.00.34.png)

**Comment by hisanshao** [comment]
目前弹窗部分是fixed处理的，在一些特定的场景样式会有一点问题，我们优化一下

**Comment by hisanshao** [comment]
你刚说的那个export 确实有问题，我们下个版本发布的时候修复
