### ISSUE TITLE
DropdownMenu 间距太大 无法使用

### ISSUE THREAD

**Issue by skyliwq** [AntmJS/vantui#123]
微信开发者工具 显示效果

![image](https://tunger.oss-cn-beijing.aliyuncs.com/%E6%88%AA%E5%B1%8F2021-12-15%2016.00.34.png)

iPhone xr 真机显示效果
![image](https://tunger.oss-cn-beijing.aliyuncs.com/WechatIMG336.jpeg)

实测场景问题还是一堆 无法在生产环境下使用，希望尽快解决

![image](https://tunger.oss-cn-beijing.aliyuncs.com/ww7.jpg)

**Comment by skyliwq** [comment]
小问题太多了 根本无法在生产环境使用 放弃了

**Comment by hisanshao** [comment]
好的哈，选择自己能接受的库才是最重要的。希望以后你再回来看的时候这个组件库能满足你的需求 @skyliwq

**Comment by hisanshao** [comment]
1.4.5修复
