### ISSUE TITLE
Tabbar 激活样式匹配问题

### ISSUE THREAD

**Issue by LiQing-He** [AntmJS/vantui#125]
**BUG描述**
tabbar激活样式匹配错误，与当前active不匹配

**复现步骤**
当把 Tabbar 当做自定义tabbar时，每个tabbar第一次点击时，样式正常（例如从最左边tab点到最右边）。第二次点击tab时，激活样式匹配错误（从右到左）

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by LiQing-He** [comment]
补充一下，是调用的Taro.switchTab

**Comment by hisanshao** [comment]
这个tabbar是自己实现的tabbar，不能使用switchTab的哦。如果你用用这个组件，建议你把tab页面作为组件来切换。如果需要用switchTab，就得使用小程序原生的tabbar配置
