### ISSUE TITLE
taro 支付宝小程序异常

### ISSUE THREAD

**Issue by nbsupermario** [AntmJS/vantui#126]
**BUG描述**
import { SwipeCell } from '@antmjs/vantui';
引入后回导致支付宝小程序 控制台 报
 TypeError: Object is not a function

**复现步骤**

**期望结果**

**实际结果**

**截图**

![image](https://user-images.githubusercontent.com/63351606/146357755-573c1510-0f42-43f1-aadd-d02de7ca05f0.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
https://github.com/AntmJS/vantui/blob/main/packages/vantui-demo/config/webpack/globalLoader.js 看下这里的使用

**Comment by hisanshao** [comment]
你是不是配置了useBuiltIns: 'usage'。截图的错误是Taro本身的错，你可以拉一个新的工程先不要装vantui组件跑一下。如果你需要处理polyfill建议你直接拷贝vantui-demo的config目录和babel.config.js。这个也是我们现在在用的配置，是可以正常运行的。

**Comment by hisanshao** [comment]
![image](https://user-images.githubusercontent.com/26359618/146520540-b67d8d88-2a5e-4043-b9a0-fa2aec49f351.png)
你是参考这个的吗

**Comment by nbsupermario** [comment]
直接在现用工程中install 直接使用组件的，尝试 https://github.com/AntmJS/vantui/blob/main/packages/vantui-demo/config/webpack/globalLoader.js  发现加入后 ，支付宝还是会提示“TypeError: Object is not a function”，微信中没问题。
错误 定位 是支付宝中global.Object 找不到，最后解决方案，把用到组件源代码放到项目里面，感谢回复！

**Comment by hisanshao** [comment]
你在globalLoader.js把Object加进去就行了。那个文件就是处理global的问题的 @nbsupermario

**Comment by nbsupermario** [comment]
> 你在globalLoader.js把Object加进去就行了。那个文件就是处理global的问题的 @nbsupermario

ok 我再尝试下

**Comment by hisanshao** [comment]
你可以看下demo工程的webpack配置，里面已经兼容了支付宝报错的问题了的。你直接按示例工程跑支付宝是可以的

**Comment by hisanshao** [comment]
或者你可以把demo的整个config+webpack的配置拷贝过去，应该是可以的

**Comment by hisanshao** [comment]
已修复，可以重新拉下temptaro的仓库代码
