### ISSUE TITLE
taro 引入 @antmjs/vantui, Toast/Dialog 不能正常使用

### ISSUE THREAD

**Issue by lliuYuuan** [AntmJS/vantui#127]
**BUG描述**
 Toast/Dialog 不能正常使用

**复现步骤**
按照文档安装的 @antmjs/vantui, babel-plugin-import, 按需加载 Toast无法使用,Rate/Button 可以使用

**期望结果**
![image](https://user-images.githubusercontent.com/28880291/146379883-c51a2e9f-8136-4739-bb10-f7d9388ac86e.png)

**实际结果**
![image](https://user-images.githubusercontent.com/28880291/146380160-378b4086-e5fb-4c6e-a9b8-1fbe8c6112d8.png)

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
JSX里面缺少  <Toast id="vanToast" />

**Comment by zuolung** [comment]
缺少
```jsx
  <Toast id="vanToast" />
```

**Comment by hisanshao** [comment]
<Toast id="van-toast"></Toast> 需要在jsx里面添加组件才能用的哦，建议这种可以用原生的，即直接调用Taro.showToast({})就好了
