### ISSUE TITLE
PowerScrollView ，生产环境异常

### ISSUE THREAD

**Issue by LiQing-He** [AntmJS/vantui#134]
**BUG描述**
生产环境编译，PowerScrollView 抛出错误
vendors.js? [sm]:formatted:1 TypeError: Cannot read property 'now' of undefined
列表内容无法显示

**复现步骤**
**期望结果**
**实际结果**
**截图**
<img width="1519" alt="DC2E610F-62C5-4638-BCBA-94D61AC02B2E" src="https://user-images.githubusercontent.com/75653843/146751230-2fd2ec9d-33d9-4ddc-b4ab-6cdb421a56cf.png">

**环境**
生产环境

**附加信息**

**Comment by Banlangenn** [comment]
把小程序开发者工具的es6 转 es5关掉

**Comment by Banlangenn** [comment]
https://github.com/NervJS/taro/issues/8098#issuecomment-731915642

**Comment by yanchengqu** [comment]
遇到楼上同样报错

**Comment by Banlangenn** [comment]
> 把小程序开发者工具的es6 转 es5关掉

**Comment by Banlangenn** [comment]
https://github.com/AntmJS/vantui/issues/134#issuecomment-997832227

这个方案不能解决吗

**Comment by yanchengqu** [comment]
> [#134 (comment)](https://github.com/AntmJS/vantui/issues/134#issuecomment-997832227)
> 
> 这个方案不能解决吗

不能解决

**Comment by yanchengqu** [comment]
> [#134 (comment)](https://github.com/AntmJS/vantui/issues/134#issuecomment-997832227)
> 
> 这个方案不能解决吗

Taro运行命令： taro build --type weapp --watch 可以。运行命令：taro build --type weapp --blended 不行

**Comment by Banlangenn** [comment]
好的， 我想一下怎么一劳永逸的把这个问题解决掉
