### ISSUE TITLE
SwipeCell组件左右滑的选择和删除无样式

### ISSUE THREAD

**Issue by ruliguowan** [AntmJS/vantui#135]
**BUG描述**
![image](https://user-images.githubusercontent.com/69052175/146864241-71355578-cd1f-447a-8608-a27970e10dd4.png)
选择和删除没有样式效果，查看节点确实是没有相关样式

**复现步骤**
    <SwipeCell
                                        rightWidth={65}
                                        leftWidth={65}
                                        renderLeft={(
                                            <View>
                                                选择
                                            </View>
                                        )}
                                        renderRight={(
                                            <View>
                                                删除
                                            </View>
                                        )}
                                    >
                                        <View className="common_use_list"></View>
                                    </SwipeCell>

**期望结果**
如dom

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/69052175/146864718-4a7b3318-8c9d-42fc-b5b7-21347a53f34a.png)

**环境**
vant 1.4.2

**附加信息**

**Comment by hisanshao** [comment]
需要自己实现哦，因为每个人的需求都是不一样的，所以就留给你们自己设置了。或者你可以去vantui-demo里面看下demo的实现

**Comment by ruliguowan** [comment]
是的，发现是要自己实现的，所以把Lssue删除了

发自我的iPhone
