### ISSUE TITLE
PowerScrollView,下拉刷新异常

### ISSUE THREAD

**Issue by LiQing-He** [AntmJS/vantui#137]
**BUG描述**
在列表任意位置，缓慢下拉（快速不会），释放后会触发PowerScrollView 下拉刷新，但当前未处于列表顶部。
开发工具鼠标拖动下拉可复现（滑轮不会触发），真机调试可复现问题

**复现步骤**

**期望结果**
应只在列表顶部下拉才触发下拉刷新

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by Banlangenn** [comment]
试过，无法复现
--
1. 可以小程序搜一下vantui （副标题：Taro版UI组件库），试一下能否复现, 不能复现可能就是写法问题
2. 加入快速沟通群
3. 提供最小复现demo

**Comment by Banlangenn** [comment]
可以讲一下解决方案， 方便其他人遇到，可以搜到解决办法

**Comment by LiQing-He** [comment]
问题是因为没有给PowerScrollView设置高度，设了之后就正常了。

**Comment by LiQing-He** [comment]
不过PowerScrollView的emptyImage和emptyDescription在ts下定义是必填的，示例未体现
