### ISSUE TITLE
所有组件px单位在taro 的 h5 配置中转换不了， 已加了 esnextModules: ['@antmjs/vantui'] 却不行 H5 显示与小程序的不一致，用不了

### ISSUE THREAD

**Issue by liujiaaoHub** [AntmJS/vantui#138]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by hisanshao** [comment]
用的是Taro开发的吗？是的话参考下vantui-demo工程的配置。如果是纯H5的参考react-demo

**Comment by ryan6015** [comment]
esnextModules: ['@antmjs']

**Comment by ryan6015** [comment]
esnextModules: ['@antmjs']
我之前也是不行，改成这样可以了。你试试

**Comment by hisanshao** [comment]
修复过了，因为windows系统下的路径分隔符不是/所以匹配不到，改成[/@antmjs[\\/]vantui/]就好了
