### ISSUE TITLE
Uploader 组件在h5端调不起来， 点击没有任可反应，这个组件只支持小程序吗？

### ISSUE THREAD

**Issue by liujiaaoHub** [AntmJS/vantui#144]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by hisanshao** [comment]
![image](https://user-images.githubusercontent.com/26359618/147806827-1fe5be1a-19df-45d2-b9f5-597a72f999f3.png)
可以的啊

**Comment by hisanshao** [comment]
直接进demo拷贝代码试试。文档可能没有更新
