### ISSUE TITLE
tabs  swipeable 为true，滑动效果差

### ISSUE THREAD

**Issue by iSept** [AntmJS/vantui#146]
**BUG描述**
Tab 标签页 tabs 属性 swipeable 为true，模拟器和真机实测滑动效果非常差，基本无法来回滑动切换tab

**复现步骤**
```
<Tabs swipeable={ true }>
    <Tab title="标签 1">
      内容 1
    </Tab>
    <Tab title="标签 2">
      内容 2
    </Tab>
    <Tab title="标签 3">
      内容 3
    </Tab>
    <Tab title="标签 4">
      内容 4
    </Tab>
  </Tabs>
```

**期望结果**
来回滑动切换tab流畅

**实际结果**
滑动效果差

**截图**

**环境**
iPhone8plus 14.2 微信小程序

**附加信息**
另外，希望Tab开放自定义头部，文档描述清楚些

**Comment by Banlangenn** [comment]
https://github.com/AntmJS/vantui/pull/158
