### ISSUE TITLE
Trao3.x  react native 如何使用

### ISSUE THREAD

**Issue by techistoner** [AntmJS/vantui#149]
"templateInfo": {
    "name": "react-native",
    "typescript": false,
    "css": "sass"
  },
taro init工程信息如上
weapp没问题
npm run dev:rn
npm run ios
报错如图:
transform[stdout]: node_modules/@antmjs/vantui/es/col/index.css
transform[stdout]: 1:10 ⚠  无效的 React Native 样式属性 "float" (taro-rn/css-property-no-unknown) [stylelint]
transform[stdout]: 1:21 ⚠  无效的 React Native 样式属性 "box-sizing" (taro-rn/css-property-no-unknown) [stylelint]
transform[stdout]: 
transform[stdout]: 警告  "float" 不是一个有效的 React Native 样式属性
transform[stdout]: StyleSheet van-col: {
transform[stdout]:   "float": "left",
transform[stdout]:   "boxSizing": "border-box"
transform[stdout]: }  entry file: node_modules/@antmjs/vantui/es/col/index.css

是否是还未支持taro 下 rn直接使用

**Comment by hisanshao** [comment]
不支持React Native
