### ISSUE TITLE
钉钉小程序平台编译报错 TypeError: i is not a function

### ISSUE THREAD

**Issue by brady2037** [AntmJS/vantui#150]
**BUG描述**
钉钉小程序平台编译报错

**复现步骤**
基于taro3.3.19版本创建 typescript + less 模板项目，添加vantui依赖，添加钉钉小程序编译插件，运行编译命令，使用小程序开发者工具IDE打开，编译报错

**期望结果**
钉钉小程序正常运行

**实际结果**
运行钉钉小程序编译失败

**截图**
![报错](https://lance-img.nos-eastchina1.126.net/image/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220105115426.png)

**环境**
node：v14.18.2
npm：6.14.15
Taro： v3.3.19

**附加信息**

项目链接：[测试项目](https://github.com/brady2037/vantui-test/tree/main)

**Comment by hisanshao** [comment]
首先确认下i是你自己代码报的错还是内部报的，如果是内部报的，可以看下temptaro或者vantui-demo的config配置文件夹。

**Comment by lppoi** [comment]
同样的问题 copy config文件到项目直接编译报错启动不起来（webpack的问题 忽略）  i 应该就是内部报错 
1.babel.config的useBuiltIns:false
2.编辑器报错
![uTools_1642398832162](https://user-images.githubusercontent.com/64509267/149715221-e6a1747e-f5f6-4a1b-98ad-dc285b429d3e.png)
![uTools_1642398777115](https://user-images.githubusercontent.com/64509267/149715228-a2e241c8-4204-413d-8f62-68937dcfc8a0.png)
![uTools_1642398749590](https://user-images.githubusercontent.com/64509267/149715230-0caf0ddc-8580-44f6-a25a-940612a1bb3a.png)
2.1TypeError: i is not a function
    at t.exports (index.js:2)
    at t.exports (index.js:2)...

页面引了个button组件
page 'pages/index/index' not found!

**Comment by lppoi** [comment]
@hisanshao 大佬您好 帮忙可以看一下错误

**Comment by hisanshao** [comment]
你直接拉temptaro的仓库代码试试，我之前在本地试过，没复现出来 @lppoi

**Comment by hisanshao** [comment]
我拉你的测试项目再试一下看

**Comment by lppoi** [comment]
![uTools_1642399974059](https://user-images.githubusercontent.com/64509267/149717012-85ca31b9-71f9-4e02-951a-577ff7fd1a28.png)
拉了temptaro代码直接运行也是i错误 @hisanshao 
watch:dd运行是Object is not a function；  dev:dd是i is not a function；

**Comment by hisanshao** [comment]
你在群里吗？你进群加我微信吧
