### ISSUE TITLE
百度/快手小程序兼容问题

### ISSUE THREAD

**Issue by CareyToboo** [AntmJS/vantui#164]
**BUG描述**
按照文档正常使用后，微信/抖音 小程序正常
# 百度小程序
百度小程序直接无法通过编译

![image](https://user-images.githubusercontent.com/15522313/151110749-a0a9e84f-7309-46f8-8e19-8dae0e10035d.png)
# 快手小程序

button  的 padding 等有异常，

**复现步骤**
必现

**期望结果**

各端编译通过，且正常展示

**实际结果**

在不同端情况不一致

**截图**

**环境**
小程序

**附加信息**

希望官网，能够展示 各端小程序的二维码，可供开发者自行体验真机效果，和发现兼容问题。
比如：微信/百度/抖音/快手/支付宝 等等
具体可以参考：[uniapp官网](https://uniapp.dcloud.io/README?id=%e5%bf%ab%e9%80%9f%e4%bd%93%e9%aa%8c)

**Comment by hisanshao** [comment]
https://github.com/AntmJS/pure-project-vantui 这个模版都测试通过了，你可以克隆下来跑跑。Object这个其实是Taro的问题，不过模版我已经兼容过了

**Comment by CareyToboo** [comment]
非常感谢～我试试
