### ISSUE TITLE
Calendar当poppable=false并type="range"并设置了defaultDate时，选择日期没有反应

### ISSUE THREAD

**Issue by qiaolin-pan** [AntmJS/vantui#172]
**BUG描述**
如题，此问题只在Calendar的poppable=false并type="range"并设置了defaultDate时存在， 永远只会显示defaultDate，选择日期没有反应，而且onSelect永远只返回一个值

**复现步骤**
```html
<Calendar
          type="range"
          defaultDate={[start, end]} // 永远只会显示defaultDate
          poppable={false}
          showConfirm={false}
          onSelect={(e) => {
            console.log(e.detail.value) // 永远只有一个值
          }}
        />
```

**期望结果**
range应该返回2个值

**实际结果**
range只返回一个值

**截图**

**环境**
"@antmjs/vantui": "^1.4.8",
"@tarojs/taro": "3.4.1",

**附加信息**

**Comment by zuolung** [comment]
defaultDate的显示后期优化，onSelect只返回点击的值，使用onConfirm获取所有

**Comment by hisanshao** [comment]
已发布@1.4.13
