### ISSUE TITLE
在自定义Tab bar中使用TabbarItem不渲染icon

### ISSUE THREAD

**Issue by jiajunmao** [AntmJS/vantui#174]
**BUG描述**
在Custom tab bar中使用TabbarItem并指定icon名字以后不渲染icon

**复现步骤**
在custom tab bar的return中定义如下代码片段，并在app.config.js中指定custom tab bar为true
```js
<Tabbar
      active={this.props.active}
      onChange={this.onChange}
      activeColor="#096dd9"
      inactiveColor="#7d7e80"
    >
      <TabbarItem
        name="label"
        icon="friends-o"
      >
        首页
      </TabbarItem>
</Tabbar>
```

**期望结果**
渲染icon

**实际结果**
在编译结果中发现icon的view node有被创建，但是icon node本身没有被创建也没有被渲染

**截图**
<img width="503" alt="image" src="https://user-images.githubusercontent.com/36388031/154194991-97df1b26-4462-41b7-ab4e-8600293ac1d3.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/36388031/154195021-b004bd0e-d871-4788-bcb8-58b021fa326c.png">

**环境**
Taro react, react版本17.0.0
```js
"@antmjs/vantui": "^1.4.12",
"@babel/runtime": "^7.7.7",
"@reduxjs/toolkit": "^1.7.2",
"@tarojs/components": "3.4.1",
"@tarojs/plugin-framework-react": "3.4.1",
"@tarojs/react": "3.4.1",
"@tarojs/runtime": "3.4.1",
"@tarojs/taro": "3.4.1",
```

**附加信息**
看了一下源代码，`<TabbarItem>`的icon name prop是直接被传参至`<Icon>`中的name prop。但是在官方文档中name prop的值显示为`friendsO`而不是`friends-o`，或许需要修正

**Comment by jiajunmao** [comment]
描述修订：一开始的代码片段没有包括icon props。已修正。

**Comment by hisanshao** [comment]
文档问题，已修正

**Comment by zzswang** [comment]
@jiajunmao 

能麻烦问一下 结合 `@AntmJs/vantui` 的自定义 tab 怎么写么？是不是有相关文档？taro 里的例子都是使用 image 作为素材的。

 主要是不知道 app.config.js 里的  tabBar.list 还需要写么？应该怎么写?
 
 多谢

**Comment by zzswang** [comment]
有没有例子，多谢多谢~
