### ISSUE TITLE
Calendar的poppable=false并type="range"并设置了defaultDate时，无法选择其他日期，点了没有反应。

### ISSUE THREAD

**Issue by qiaolin-pan** [AntmJS/vantui#181]
**BUG描述**
1.Calendar的poppable=false并type="range"并设置了defaultDate时，无法选择其他日期，点了没有反应。
2.Calendar的poppable=false并type="range"并设置了defaultDate时，onSelect只返回一个值。
代码如下：

**复现步骤**
```html
<Calendar
  type="range"
  defaultDate={['2022-02-19', '2022-02-22']} // 一直显示这个日期，点不了其它日期，点了没反应
  allowSameDay
  poppable={false}
  showTitle={false}
  showConfirm={false} // 不想显示confirm按钮，我想做一些自定义修改
  onSelect={(e) => {
    console.log(e) // 只返回选择的值，我如何获取所有值？
  }}
/>
```

**期望结果**
设置了defaultDate也可以选择其它日期，并且onSelect可以返回所有值

**实际结果**
设置了defaultDate无法选择其它日期，并且onSelect只返回一个值

**截图**

**环境**
"@antmjs/vantui": "^1.4.8"

**附加信息**

**Comment by hisanshao** [comment]
升级一下版本

**Comment by qiaolin-pan** [comment]
@hisanshao 问题并没有解决啊，"@antmjs/vantui": "^1.4.14"还是这样的问题
