### ISSUE TITLE
Cell 组件中对于 .van-hairline--surround::after 的样式定义冗余了

### ISSUE THREAD

**Issue by sojuker** [AntmJS/vantui#187]
**BUG描述**
在项目中引用 Button， Cell 组件，并指定 Button 使用 hairline。
会发现 .van-hairline--surround::after 样式定义出现两遍

**复现步骤**
```jsx
import { Button, Cell } from "@antmjs/vantui";
export default () => {
     return (<Button className="button" plain hairline type="primary">
        细边框按钮
     </Button>)
}
```

**期望结果**
 .van-hairline--surround::after 只出现一遍

**实际结果**
出现了两遍

**截图**
![wecom-temp-086f63cc020cae86314c7a1488370a52](https://user-images.githubusercontent.com/2988612/155268501-921f4552-0a11-405f-a340-efaf36dbab98.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
把src/style/index.less文件下面的@import '@antmjs/vantui/es/style/base.less'; 注释掉或者放到app.less就行了。这里面放了一些基础的less方法，用不到的话注释掉就好了，业务上想用的话放app.less里面
