### ISSUE TITLE
是否可以加入Taro+Vue 3的支持？

### ISSUE THREAD

**Issue by justinlu** [AntmJS/vantui#190]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
是否可以加入Taro+Vue 3的支持？我们目前在使用Taro + Vue3开发小程序，希望能使用Vant。

**您是否有建议的实现方案**
目前暂时使用Vant Weapp替代，但没办法支持微信小程序以外的小程序平台

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
暂时没有计划哦
