### ISSUE TITLE
建议Tab中的title支持ReactNode

### ISSUE THREAD

**Issue by yujingwyh** [AntmJS/vantui#198]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
标题栏需要展示小标签

**您是否有建议的实现方案**
title属性增加ReactNode支持

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/13347406/157159520-d80c489b-d13f-41c4-9fa8-16ad1a427548.png)

**Comment by Banlangenn** [comment]
代码里是支持的， 但是类型没有透出来

**Comment by yujingwyh** [comment]
会有报错
![image](https://user-images.githubusercontent.com/13347406/157618822-6feaa220-399a-430d-999b-399c59f833ec.png)
`
import {Text  } from "@tarojs/components";
import {Tab,Tabs } from "@antmjs/vantui";

export default () => {
  return (
    <Tabs>
      <Tab name={'key1'} title={<Text>title1</Text> as any}>
        1
      </Tab>
      <Tab name={'key2'} title={<Text>title2</Text> as any}>
        2
      </Tab>
   </Tabs>
  );
};

`

**Comment by Banlangenn** [comment]
需要处理一下
