### ISSUE TITLE
@antmjs/vantui的package.json中module指向es/index.esm.js，但是为什么找不到该文件

### ISSUE THREAD

**Issue by guoguolong** [AntmJS/vantui#202]
安装后 @antmjs/vantui后，查看 node_modules/@antmjs/vantui/package.json，下面是 package.json 文件乃荣片段
```json

  "license": "MIT",
  "main": "lib/index.js",
  "module": "es/index.esm.js",
  "name": "@antmjs/vantui",
```

module 指向 es/index.esm.js，然后去 es目录下查找，并没有发现 index.esm.js 这个文件，这是为什么？

**Comment by hisanshao** [comment]
你升级一下，或者重新构建一下，这个应该不是代码问题，大家都是可以的
