### ISSUE TITLE
@antmjs/vantui构建包括es和lib目录，看起来完全一样，那有什么区别呢？

### ISSUE THREAD

**Issue by guoguolong** [AntmJS/vantui#203]
查看 node_modules/@antmjs/vantui下的 es 和 lib 目录，代码是一样的，那为什么要构建两个同样的目录呢？

**Comment by hisanshao** [comment]
编译lib有点问题，应该输出commonjs的。现在es和lib输出的都是esmodules了。我们修复一下

**Comment by hisanshao** [comment]
脚本已更新
