### ISSUE TITLE
在Taro中Circle组件setState设置ready为true的时机会错过，导致canvas不会渲染

### ISSUE THREAD

**Issue by wxwqslsdsh** [AntmJS/vantui#205]
**BUG描述**
当子组件是按需加载或者异步加载的时候，无法触发useReady生命周期钩子

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by Chitanda60** [comment]
运行环境或用例代码填下

**Comment by brady2037** [comment]
<View className='index'>

        {this.state.current == 0 && <BoardIndexPage/>}

        {this.state.current == 1 && <Circle
          value={this.state.circleValue}
          layerColor='#eeeeee'
          color='#ee0a24'
          text='颜色定制'
        />}

**Comment by brady2037** [comment]
> 运行环境或用例代码填下
同样遇到了问题，场景是Circle初始不显示，更改state为1后显示， 此时CoverView可以显示文字，圆环不显示

运行环境：
微信小程序环境，框架taro+react、版本："@antmjs/vantui":“1.6.1”

示例代码：
constructor() {
    super();
    this.state = {
      current: 0,
    }
  }
     
 <View className='index'>

        {this.state.current == 0 && <BoardIndexPage/>}

        {this.state.current == 1 && <Circle
          value={this.state.circleValue}
          layerColor='#eeeeee'
          color='#ee0a24'
          text='颜色定制'
        />}
</View>
