### ISSUE TITLE
Taro React+Sass 模板编译失败

### ISSUE THREAD

**Issue by brady2037** [AntmJS/vantui#211]
**BUG描述**
使用 React+Sass创建模板项目，引入vantui编译失败，报错：
```
🙅   编译失败. 2022/4/7 上午11:14:16

./src/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):   
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
2 │ import "@antmjs/mini-fix"
  │                          ^
  ╵
  src\app.scss 2:26  root stylesheet

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**复现步骤**
使用pure-project-vantui项目模板
`src/app.less` 修改为`src/app.scss`

package.json下
```
"templateInfo": {
        "name": "default",
        "typescript": true,
        "css": "less"
    }
```
修改为
```
"templateInfo": {
        "name": "default",
        "typescript": true,
        "css": "sass"
    }
```
编译微信平台报错

**期望结果**
使用Taro React + Sass模板编译通过 

**实际结果**
使用Taro React + Sass模板编译失败 

**截图**

**环境**

Taro CLI 3.4.4 environment info:
System:
OS: Windows 10
Shell: Windows PowerShell
Binaries:
Node: 14.18.2 
npm: 6.14.15
npmPackages:
"dependencies": {
    "@antmjs/mini-fix": "^1.17.6",
    "@antmjs/vantui": "^1.5.1",
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.4.4",
    "@tarojs/react": "3.4.4",
    "@tarojs/runtime": "3.4.4",
    "@tarojs/taro": "3.4.4",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@antmjs/plugin-mini-fix": "^1.17.6",
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.4.4",
    "@tarojs/mini-runner": "3.4.4",
    "@tarojs/plugin-framework-react": "3.4.4",
    "@tarojs/plugin-platform-alipay-dd": "^0.1.2",
    "@tarojs/plugin-platform-kwai": "^1.0.1",
    "@tarojs/webpack-runner": "3.4.4",
    "@types/react": "^17.0.2",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-plugin-import": "^1.13.3",
    "babel-preset-taro": "3.4.4",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.4.4",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0",
    "typescript": "^4.1.0"
  }

**附加信息**

**Comment by hisanshao** [comment]
@antmjs/plugin-mini-fix这个插件的正则匹配有问题。 模版已修复了

**Comment by brady2037** [comment]
> @antmjs/plugin-mini-fix这个插件的正则匹配有问题。 模版已修复了

Thanks♪(･ω･)ﾉ
