### ISSUE TITLE
在dumi框架中使用，图片无法解析

### ISSUE THREAD

**Issue by zhouzyc** [AntmJS/vantui#212]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/18420689/162148395-794c4369-d71c-480c-99c5-c737ed43a70b.png">

**环境**

**附加信息**

**Comment by hisanshao** [comment]
看不出效果啊，这个和框架应该无关。可以自己测试一下，或者提供一个可复现的demo链接过来

**Comment by zhouzyc** [comment]
采用额外的方式来解决
