### ISSUE TITLE
Taro中Circle组件异步显示空白！setState设置ready为true的时机会错过，导致canvas不会渲染

### ISSUE THREAD

**Issue by brady2037** [AntmJS/vantui#229]
**BUG描述**
当子组件是按需加载或者异步加载的时候，无法触发useReady生命周期钩子

**复现步骤**
使用pure-project-vantui项目模板，修改代码如下：

```
export default function Index() {
  const [isShow, setIsShow] = useState();
  useEffect(() => {
    //模拟接口请求
    setTimeout(() => {
      setIsShow(true)
    }, 2000)
  }, [])
  return (
    <View className='index'>
      <View><Button type='primary'>Hello world!</Button></View>
      <View>上面的按钮的颜色已经通过全局主题重写覆盖了，参见src/style/index.less</View>

      <Circle
        value={30}
        layerColor="#eeeeee"
        color="#ee0a24"
        text="Circle跟随页面显示"
      />

      {/*模拟接口请求成功后显示*/}
      {isShow && <View>
        <Circle
          value={30}
          layerColor="#eeeeee"
          color="#ee0a24"
          text="Circle延迟显示"
        />
      </View>}

    </View>
  )
}
```

**期望结果**
Circle组件异步显示正常

**实际结果**
Circle组件异步显示空白

**截图**
[![Snipaste-2022-04-22-13-56-09.png](https://i.postimg.cc/w38KBFF1/Snipaste-2022-04-22-13-56-09.png)](https://postimg.cc/D4gpjr9h)

**环境**
Taro CLI 3.4.4 environment info:
System:
OS: Windows 10
Shell: Windows PowerShell
Binaries:
Node: 14.18.2
npm: 6.14.15
npmPackages:
"dependencies": {
"@antmjs/mini-fix": "^1.17.6",
"@antmjs/vantui": "^1.5.1",
"@babel/runtime": "^7.7.7",
"@tarojs/components": "3.4.4",
"@tarojs/react": "3.4.4",
"@tarojs/runtime": "3.4.4",
"@tarojs/taro": "3.4.4",
"react": "^17.0.0",
"react-dom": "^17.0.0"
},
"devDependencies": {
"@antmjs/plugin-mini-fix": "^1.17.6",
"@babel/core": "^7.8.0",
"@tarojs/cli": "3.4.4",
"@tarojs/mini-runner": "3.4.4",
"@tarojs/plugin-framework-react": "3.4.4",
"@tarojs/plugin-platform-alipay-dd": "^0.1.2",
"@tarojs/plugin-platform-kwai": "^1.0.1",
"@tarojs/webpack-runner": "3.4.4",
"@types/react": "^17.0.2",
"@types/webpack-env": "^1.13.6",
"@typescript-eslint/eslint-plugin": "^4.15.1",
"@typescript-eslint/parser": "^4.15.1",
"babel-plugin-import": "^1.13.3",
"babel-preset-taro": "3.4.4",
"eslint": "^6.8.0",
"eslint-config-taro": "3.4.4",
"eslint-plugin-import": "^2.12.0",
"eslint-plugin-react": "^7.8.2",
"eslint-plugin-react-hooks": "^4.2.0",
"stylelint": "9.3.0",
"typescript": "^4.1.0"
}

**附加信息**

**Comment by hisanshao** [comment]
1.9.2已修复
