### ISSUE TITLE
请问，组件库的designWidth支持调整不？

### ISSUE THREAD

**Issue by weiwenhuaming** [AntmJS/vantui#232]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

目前我们项目使用的 Taro 3.+版本，计划引入 vantui，不过在接入过程中发现，组件尺寸过大。
项目中的designWidth是 375，vanui 是 750。有快速适配的方案不？

**您是否有建议的实现方案**

也同时尝试接入过 taroifyui，也存在同样问题，不过通过`config/index.js`中配置下列代码解决了。如果可以，希望 vantui 也能提供下。
```
  sass: {
    // 适配 taroify 设计稿过大问题
    data: "$hd: 1;"
  }
```

**其它帮助我们理解您需求的描述、截图**

<img width="327" alt="企业微信截图_778d83a0-1b06-4a45-9bc2-9469262bfac0" src="https://user-images.githubusercontent.com/16578617/165208067-e867661e-a8fb-4e34-bfc7-d2c4b371c8c3.png">

**Comment by hisanshao** [comment]
参考 同时兼容Vant Weapp部分 https://antmjs.github.io/vantui/#/quickstart#tong-shi-jian-rong-vant-weapp

**Comment by chendong-xie** [comment]
@weiwenhuaming 请问你解决了吗

**Comment by lzfxxx** [comment]
链接现在是打不开的，可以直接去 https://antmjs.github.io/vantui/#/quickstart 然后找到 **兼容 Vant Weapp 以及 兼容项目配置的尺寸设置为非 750 导致组件库的样式偏大偏小问题** 部分
