### ISSUE TITLE
Circle 在微信小程序上不显示

### ISSUE THREAD

**Issue by ningxzx** [AntmJS/vantui#236]
**BUG描述**
在taro项目中使用了taro，没有显示canvas，仅显示了文字

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by ningxzx** [comment]
conic-gradient

使用这个自己画了一个

**Comment by Chitanda60** [comment]
@ningxzx 补充下复现步骤
