### ISSUE TITLE
PowerScrollView自定义renderLoading不生效

### ISSUE THREAD

**Issue by ccj-csf** [AntmJS/vantui#237]
**BUG描述**
自定义不生效，最开始使用版本1.8.3，后升级到最新1.9.1依然无效

**复现步骤**

**期望结果**

期望能够自定义加载中样式
**实际结果**
实际并不会生效，加载更多能够正常执行

**截图**
![code](https://user-images.githubusercontent.com/86881672/165689122-a49f398d-d031-4d97-8bbb-1088d594850e.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
renderLoading?: React.ReactNode 直接传递节点过去就好了，不是传方法的
