### ISSUE TITLE
Collapse组件给value提供初始值时，初始值对应的CollapseItem没有展开

### ISSUE THREAD

**Issue by luqiaoyun** [AntmJS/vantui#239]
**BUG描述**
在taro中使用Collapse时，给Collapse给定了初始值，但是初始值对应的CollaseItem没有展开，效果如下图：

![1651202243(1)](https://user-images.githubusercontent.com/28926372/165880301-613639b4-af81-4ef5-9acc-332051f4bbb1.png)
![1651202278(1)](https://user-images.githubusercontent.com/28926372/165880351-4519960c-ec62-4eed-b89d-2820bbc47aeb.png)

此时箭头的方向是正确的，但是内容没有显示出来

debugger调试发现，在首次渲染的时候，collapse-item/animate.js 里的方法setContentAnimate中调用的useAnimation方法中传递的height值为undefined

![1651202548(1)](https://user-images.githubusercontent.com/28926372/165880708-07665177-cca2-4449-af6e-8689379180e2.png)

而useAnimation里对height的判断条件是height === 0，所以没能匹配上

![1651202736(1)](https://user-images.githubusercontent.com/28926372/165880960-3ad2568f-ca73-483b-ba96-287abf7cd5bc.png)

**Comment by Chitanda60** [comment]
@luqiaoyun 项目的taro和vantui版本是多少?

**Comment by luqiaoyun** [comment]
> 



> @luqiaoyun 项目的taro和vantui版本是多少?



> 

taro版本3.3.12     vantui版本1.8.3

**Comment by hisanshao** [comment]
1.9.2已修复
