### ISSUE TITLE
Tabbar 标签栏的TabbarItem 自定义图标 在当前TabbarItem被选中时不显示

### ISSUE THREAD

**Issue by 1099961262** [AntmJS/vantui#243]
**BUG描述**
TabbarItem 自定义图标 在当前TabbarItem被选中时不显示选中图标只显示了文字
![image](https://user-images.githubusercontent.com/32692103/167355010-ee9286b2-f2f7-47ed-afa9-8aafde67ec7f.png)

**复现步骤**

>  <Tabbar active={active} onChange={onChangeActive}>
          <TabbarItem
            renderIcon={
              <Block>
                <Image
                  src={information}
                  mode="aspectFit"
                  style="width: 30px; height: 18px;"
                ></Image>
              </Block>
            }
            renderIconactive={
              <Block>
                <Image
                  src={information_active}
                  mode="aspectFit"
                  style="width: 30px; height: 18px;"
                ></Image>
              </Block>
            }
          >
            自定义
          </TabbarItem>
          <TabbarItem icon="search">标签</TabbarItem>
          <TabbarItem icon="setting-o">标签</TabbarItem>
        </Tabbar>

**期望结果**
渲染选中时的自定义图片

**实际结果**
在编译结果中发现icon的view node有被创建，但是icon node本身没有被创建也没有被渲染

**截图**
![image](https://user-images.githubusercontent.com/32692103/167355273-9e5c7825-ba5b-489e-b04a-51aa1afbf3ef.png)

**环境**
Taro react, react版本17.0.0

> "@antmjs/vantui": "^1.9.2",
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.4.8",
    "@tarojs/plugin-framework-react": "3.4.8",
    "@tarojs/react": "3.4.8",
    "@tarojs/runtime": "3.4.8",
    "@tarojs/taro": "3.4.8",

**附加信息**

**Comment by hisanshao** [comment]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/26359618/167390664-3ec9abf0-563a-420b-889f-4605f9d78522.png">
大小写错了吧

**Comment by hisanshao** [comment]
是文档写的有问题，你改成renderIconActive
