### ISSUE TITLE
h5模式下，field组件，type=“number”，输入框无法输入字符

### ISSUE THREAD

**Issue by leihongw** [AntmJS/vantui#266]
**BUG 描述**
版本：1.9.5，h5模式下，field组件，属性type=“number”，field无法输入任意字符。onChange打印结果，为空白字符。测试如果修改type=“text”则表现正常。

**复现步骤**

**期望结果**
可以正确输入数字

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
1.9.6修复
