### ISSUE TITLE
文档字体能否加个默认非衬线字体

### ISSUE THREAD

**Issue by lzfxxx** [AntmJS/vantui#279]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在英文macOS下面是衬线字体（宋体）有点丑
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/12368329/175502645-6bf9e776-f930-4920-a69a-cbbedacf329f.png">

**您是否有建议的实现方案**
文档加个默认非衬线字体

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
已更新，试试
