### ISSUE TITLE
Tabbar   icon 没效果

### ISSUE THREAD

**Issue by whqgo** [AntmJS/vantui#307]
![image](https://user-images.githubusercontent.com/100900895/181667039-c48ea775-ec55-40fa-af72-1984698ce3e5.png)

![image](https://user-images.githubusercontent.com/100900895/181667061-d8461f65-c856-49cb-b8d8-aec9690cb019.png)

**Comment by hisanshao** [comment]
组件库什么版本

**Comment by whqgo** [comment]
^1.9.15",

**Comment by whqgo** [comment]
> 组件库什么版本

^1.9.15",

**Comment by hisanshao** [comment]
看下demo吧，文档里面的demo都是可以显示的啊

**Comment by Wangbaoqi** [comment]
这个确实有问题 Icon 组件的样式默认没有引入 需要手动引入才会生效 

这个在 taroify 中没有问题
