### ISSUE TITLE
Dialog 弹出框在taro3.5.2中RN端报错

### ISSUE THREAD

**Issue by Aliom252181** [AntmJS/vantui#314]
**BUG 描述**
Dialog 弹出框在taro3.5.2中RN端报错
**复现步骤**
import react, { FC, useContext, useState } from "react";
import { observer } from 'mobx-react-lite';
import { RootStoreContext } from '@/store/index';
import { View, Text, Input } from '@tarojs/components';
import { useDidShow } from '@tarojs/taro';

import NativeButton from "@/components/service/nativeButton/nativeButton";
import { Dialog } from '@antmjs/vantui'

import './counter.scss';

interface IProps { };

const Counter: FC<IProps> = (props) => {
  const store = useContext(RootStoreContext);
  const [value, setValue] = useState('')

  const confirm = react.useCallback(() => {
    Dialog.confirm({
      title: '标题',
      message: (
        <Input
          placeholder="请输入内容"
          value={value}
          onInput={(e) => setValue(e.detail.value)}
        />
      ),
      selector: 'vanDialog0',
    }).then((value) => {
      console.log('dialog result', value)
    })
  }, [value])

  return (
    <>
      <View className='index-container'>
        <Text>{store.counterStore.value}</Text>
        <NativeButton BindClick={confirm}>确认弹窗</NativeButton>
      </View>
      <Dialog id="vanDialog0"/>
    </>
  )
};
export default observer(Counter);
**期望结果**
正常打包或预览
**实际结果**
报错
RuntimeError: abort(SyntaxError: node_modules/@antmjs/vantui/es/dialog/style/less.js: /Volumes/T5/Code/gc-nativeapp-cli/taro-rn-h5-mini-ts/node_modules/@antmjs/vantui/es/dialog/style/less.js: Duplicate declaration "indexLessStyleSheet1"
**截图**
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/49222345/183336450-ead77a44-7f4f-4903-8d43-018936767ce9.png">

**环境**
Taro v3.5.2

  Taro CLI 3.5.2 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.6.0/bin/yarn
      npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.2 => 3.5.2 
      @tarojs/components: 3.5.2 => 3.5.2 
      @tarojs/helper: 3.5.2 => 3.5.2 
      @tarojs/plugin-framework-react: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-alipay: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-jd: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-qq: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-swan: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-tt: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-weapp: 3.5.2 => 3.5.2 
      @tarojs/react: 3.5.2 => 3.5.2 
      @tarojs/rn-runner: 3.5.2 => 3.5.2 
      @tarojs/router: 3.5.2 => 3.5.2 
      @tarojs/runtime: 3.5.2 => 3.5.2 
      @tarojs/shared: 3.5.2 => 3.5.2 
      @tarojs/taro: 3.5.2 => 3.5.2 
      @tarojs/taro-h5: 3.5.2 => 3.5.2 
      @tarojs/taro-rn: 3.5.2 => 3.5.2 
      babel-preset-taro: 3.5.2 => 3.5.2 
      eslint-config-taro: 3.5.2 => 3.5.2 
      expo: ~46.0.1 => 46.0.2 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 
**附加信息**

**Comment by hisanshao** [comment]
不支持RN哦
