### ISSUE TITLE
Area组件选择了省之后市没有跟着联动

### ISSUE THREAD

**Issue by mumuwooo** [AntmJS/vantui#322]
**BUG 描述**
taro小程序里引入Area组件，用的官方提供的areaList数据，无论是否嵌套在popup里，选择省之后都无法联动到市。
已经排除所有干扰，单纯空白页添加组件也能复现。

**复现步骤**
import React from 'react'
import Taro from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import { useNavigationBar } from 'taro-hooks'
import { areaList } from '@vant/area-data'
import {  Area,} from "@antmjs/vantui"; 
import './index.scss'

const index = () => {
    const [_, { setTitle }] = useNavigationBar({ title: '测试页面' })
    return (
        <View>
            <Area areaList={areaList} />
        </View>
    )
}

export default index

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/24455985/184314390-7547f739-6849-436c-8b73-e8f1e6c6ba78.png)

**环境**
    "@antmjs/vantui": "^1.9.20",
    "@tarojs/cli": "3.3.15",
    "@tarojs/components": "3.3.15",
    "@tarojs/react": "3.3.15",
    "@tarojs/runtime": "3.3.15",
    "@tarojs/taro": "3.3.15",
    "@vant/area-data": "^1.3.1",

**附加信息**

**Comment by hisanshao** [comment]
升级到3.4或者3.5试试

**Comment by mumuwooo** [comment]
> 升级到3.4或者3.5试试

我猜也是这个，于是发完了issue就去升级了一下，果然可以了🙏
