### ISSUE TITLE
折叠面板CollapseItem使用renderRightIcon没有效果

### ISSUE THREAD

**Issue by roukgbk** [AntmJS/vantui#325]
**BUG 描述**
CollapseItem使用renderRightIcon没有效果

**截图**
![image](https://user-images.githubusercontent.com/59163110/185065954-dd66c812-feae-4c4d-97d9-26f499d59424.png)
![image](https://user-images.githubusercontent.com/59163110/185066102-9adbdea0-f015-45e2-a6ca-372936a832c0.png)

**环境**
react+taro+ts

**Comment by hisanshao** [comment]
isLink设置为false clickable设置为true renderRightIcon就能用了。文档我说明一下
