### ISSUE TITLE
小程序：DatetimePicker 设置 value 无效

### ISSUE THREAD

**Issue by Deain** [AntmJS/vantui#328]
**BUG 描述**
1、初始化设置的value值，并不会默认选中；
2、选择日期时，控制台报错：`RangeError: Invalid array length`

猜测是最大最小日期超出范围所致，如果是这样，那该如何设置跨度较大的时间段呢？

**复现步骤**
```jsx
<DatetimePicker
    type="date"
    showToolbar={false}
    visibleItemCount={3}
    itemHeight={40}
    minDate={'1970-01-01 00:00:00'}
    maxDate={'2042-11-31 00:00:00'}
    value={'2022-02-02'}
/>
```

**实际结果截图**
<img width="380" alt="image" src="https://user-images.githubusercontent.com/8544120/185741508-fab08f8c-95fd-4d83-baab-088a7bd0c629.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/8544120/185741740-c0aea3e1-a0eb-4656-a75a-37ff3610084a.png">

**Comment by zuolung** [comment]
时分秒类型时间支持 xx:xx:xx, 包含日期类型的时间，须传入时间戳

**Comment by Deain** [comment]
> 时分秒类型时间支持 xx:xx:xx, 包含日期类型的时间，须传入时间戳

谢谢，时间戳可以了
