### ISSUE TITLE
请问支持react18吗？

### ISSUE THREAD

**Issue by CaanDoll** [AntmJS/vantui#329]
**BUG 描述**
taro3.5已经默认react18，使用例如Image组件会报错invalid hook

**复现步骤**
```typescript
import { Image } from "@antmjs/vantui";

export default function Index (){
  const {data} = useRequest(getCarouselAll);
  return (
    <View className='index'>
      <Swiper
        indicatorColor='#999'
        indicatorActiveColor='#333'
        circular
        indicatorDots
        autoplay>
        {data?.map(item=>{
          return  <SwiperItem key={item.uuid}>
            <Image src={completeImgUrl(item.url)} width={pxTransform(600)} height={pxTransform(300)} />
          </SwiperItem>
        })}
      </Swiper>
    </View>
  )
}
```
**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/23540471/185797581-ffb132a0-f3dd-4965-a59c-e5118357ad13.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/26359618/185827778-e62eacff-dffa-47e4-8845-3cb60a3ece8b.png">
没有报错啊，你再排查一下原因吧
