### ISSUE TITLE
小程序：Cell 设置 clickable=false 后，仍有点击效果：背景变色

### ISSUE THREAD

**Issue by Deain** [AntmJS/vantui#330]
**bug描述**
Cell类 组件，clickable=false，仍有点击效果
Field

**复现步骤**
```jsx
 <Cell
      required
      title={'请选择单位'}
      border={false}
      clickable={false}
      style={'margin: 15px -15px -10px;width:auto;'}
      renderExtra={
        <View style={Styles.row}>
          {
            ['吨', '方', '件'].map((item, i) => {
              return (
                <Unit
                  key={item}
                  text={item}
                  checked={i === unitIndex}
                  onPress={() => setUnitIndex(i)}
                />
              )
            })
          }
          <Text style={{marginLeft: 15, fontSize: 16, color: '#444'}}>/元</Text>
        </View>
      }
 />
```

**截图**
<img width="393" alt="image" src="https://user-images.githubusercontent.com/8544120/185833927-112cf2ef-7cdf-442e-97d5-1d9781a8ccc1.png">

**Comment by hisanshao** [comment]
https://antm-js.gitee.io/vantui/mobile.html#/pages/cell/index
模版是没问题的啊，这个得你具体看下clickable的className是不是被展示出来了？你先定位一下是什么原因吧，这个我看不出来具体问题

**Comment by Deain** [comment]
> https://antm-js.gitee.io/vantui/mobile.html#/pages/cell/index 模版是没问题的啊，这个得你具体看下clickable的className是不是被展示出来了？你先定位一下是什么原因吧，这个我看不出来具体问题

小程序端，hover-class 是存在的

**Comment by hisanshao** [comment]
拿你代码测试过了，没问题。应该是你自己哪里设置的样式导致的
