### ISSUE TITLE
在React项目中引入组件库

### ISSUE THREAD

**Issue by edsion11** [AntmJS/vantui#335]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

文档有对于在React项目中引入和使用组件库的说明，是否可以有一个简单的demo展示

**Comment by edsion11** [comment]
个人有一个使用CRA脚手架生成的react项目，[地址点这里](https://github.com/edsion11/react-vantui-demo)。项目使用craco来配置webpack，目前有一个问题是:基于`postcss-pxtransform`插件的转换并没有转换组件库的`px`单位，不清楚问题在哪里

**Comment by hisanshao** [comment]
仓库里面有一个demo。https://github.com/AntmJS/create-react-app-vantui
