### ISSUE TITLE
字节小程序跑不起来

### ISSUE THREAD

**Issue by qingweiSun** [AntmJS/vantui#338]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [x] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
build之后无法运行，dev可以
**复现步骤**
taro build --type tt
**期望结果**
正常运行
**实际结果**
无法运行
**截图**
<img width="528" alt="image" src="https://user-images.githubusercontent.com/16513906/188539173-5ef84516-7e72-4e9a-b254-4c6efe2b800d.png">

**环境**

**附加信息**

**Comment by hisanshao** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/26359618/188540350-49b0845e-3791-4caa-82e4-fe70e68548ec.png">

看下这些配置，报错和组件库应该没什么关系

**Comment by qingweiSun** [comment]
我检查了下是关的呢好像

**Comment by qingweiSun** [comment]
useBuiltIns: false,/*不能为usage,不然build后无法运行*/
