### ISSUE TITLE
运行 temptaro 模板项目，点击 `带tab和search的分页模版页` 按钮，跳转的新页面不存在

### ISSUE THREAD

**Issue by jiangrubin** [AntmJS/vantui#339]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

运行 temptaro 模板项目，点击 `带tab和search的分页模版页` 按钮，跳转的新页面不存在

**复现步骤**

<img width="336" alt="WeChat635ac74469f6a50f3dd0165b1af4158f" src="https://user-images.githubusercontent.com/30112163/188804406-fb44896a-e5a4-4d6f-9902-e7f00e2bfa5d.png">

**期望结果**

**实际结果**

**截图**

<img width="301" alt="WeChat4a1418d8d841342f6fd7bcc862dd0cc9" src="https://user-images.githubusercontent.com/30112163/188802806-05a8a8d5-f4e1-4f35-9a30-629e7f3aa972.png">

<img width="537" alt="WeChat5ff2df39fec70e6e7433aee511e20e85" src="https://user-images.githubusercontent.com/30112163/188802913-f49264df-515e-40f3-8375-37357724eb0c.png">

**环境**

Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm

**附加信息**

支付宝小程序开发者工具 v3.1.3

**Comment by hisanshao** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/26359618/188814893-a3474997-77c5-43bf-996c-c8ab3919e385.png">
修复过了，你可以pull一下，或者这里加下框起来的逻辑

**Comment by jiangrubin** [comment]
pure-project-vantui 模板项目中，加了这个配置不生效

**Comment by jiangrubin** [comment]
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/26359618/188814893-a3474997-77c5-43bf-996c-c8ab3919e385.png">
> 
> 修复过了，你可以pull一下，或者这里加下框起来的逻辑

pure-project-vantui 项目也有这个问题，该如何修改呢 😭

**Comment by hisanshao** [comment]
我试了，可以打开的啊
