### ISSUE TITLE
Tabs 组件 初次加载，如果active是第一个则不会显示

### ISSUE THREAD

**Issue by NgChiKin** [AntmJS/vantui#341]
**这个 Issue 涉及以下平台:**

- 

- [x]  微信小程序

**BUG 描述**
Tabs 组件 初次加载，如果active是第一个则不会显示
**复现步骤**
 < Tabs >
        < Tab title="标签 1">内容 1</ Tab>
        < Tab title="标签 2">内容 2</ Tab>
        < Tab title="标签 3">内容 3</ Tab>
        < Tab title="标签 4">内容 4</ Tab>
      </ Tabs>
**期望结果**
正常显示
**实际结果**
Tabs 组件 初次加载，如果active是第一个则不会显示
**截图**
![image](https://user-images.githubusercontent.com/57823909/189022159-34035d24-4cda-4100-b31a-ebb463cd0038.png)

**环境**
微信小程序、 Mac
  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.4 => 3.5.4 
      @tarojs/components: 3.5.4 => 3.5.4 
      @tarojs/helper: 3.5.4 => 3.5.4 
      @tarojs/plugin-framework-react: 3.5.4 => 3.5.4 
      @tarojs/plugin-platform-weapp: 3.5.4 => 3.5.4 
      @tarojs/react: 3.5.4 => 3.5.4 
      @tarojs/router: 3.5.4 => 3.5.4 
      @tarojs/runtime: 3.5.4 => 3.5.4 
      @tarojs/shared: 3.5.4 => 3.5.4 
      @tarojs/taro: 3.5.4 => 3.5.4 
      @tarojs/taro-h5: 3.5.4 => 3.5.4 
      @tarojs/webpack5-runner: 3.5.4 => 3.5.4 
      babel-preset-taro: 3.5.4 => 3.5.4 
      eslint-config-taro: 3.5.4 => 3.5.4 
      react: ^18.0.0 => 18.2.0 

**附加信息**

**Comment by hisanshao** [comment]
tabs 没添加active属性啊

**Comment by NgChiKin** [comment]
没有传active 默认不就是 active 第一个吗？添加了 active 属性如果是第一个也是一样的

**Comment by hisanshao** [comment]
是有问题，晚上会发布一版
