### ISSUE TITLE
Cascader 级联选择何时可以提供呢？

### ISSUE THREAD

**Issue by hqwlkj** [AntmJS/vantui#344]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [x] 支付宝小程序
- [x] 百度小程序
- [x] 头条小程序
- [x] 快手小程序
- [x] QQ 轻应用
- [x] Web 平台（H5）

**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/12181423/190038711-9a753256-041f-4c45-8818-0d50bdddd6e6.png)

**Comment by hisanshao** [comment]
2.1.0已支持
