### ISSUE TITLE
Popup组件overlayStyle类型

### ISSUE THREAD

**Issue by unfetteredman2020** [AntmJS/vantui#346]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Popup组件的overlayStyle属性官方文档是sting， 实际是Object类型
**复现步骤**

**期望结果**
Object
**实际结果**
string
**截图**
![image](https://user-images.githubusercontent.com/52193409/190364290-e614a739-44c7-4b73-89ab-e9405b35feec.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
2.1.0已修复
