### ISSUE TITLE
Bug: [Toast] Component children props(React.ReactNode) it's not work

### ISSUE THREAD

**Issue by wegi8** [AntmJS/vantui#349]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Taro小程序中，我写一个Toast弹窗，需要自定义，写好后我Toast.show({ children: <ErrorMsg />, selector: '#error' })，但是不起作用
<img width="254" alt="image" src="https://user-images.githubusercontent.com/43628500/190615845-346706d2-e132-4666-a105-0dc0b1a00e16.png">

**复现步骤**

**期望结果**
能将Children当作正常元素渲染

**实际结果**
<img width="254" alt="image" src="https://user-images.githubusercontent.com/43628500/190615845-346706d2-e132-4666-a105-0dc0b1a00e16.png">

**截图**
<img width="411" alt="image" src="https://user-images.githubusercontent.com/43628500/190615955-490c54ae-170e-466e-9373-8c050b02f9be.png">

**环境**
Taro dev环境

**附加信息**

**Comment by zuolung** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/28145148/190617394-f1f847c2-009c-4eb0-b4be-00367247e183.png">

**Comment by wegi8** [comment]
> <img width="547" alt="image" src="https://user-images.githubusercontent.com/28145148/190617394-f1f847c2-009c-4eb0-b4be-00367247e183.png">
> 
> 

我可能没有描述清楚，这一段在我的app.tsx里，而show方法那一段在我的请求拦截器里，双块代码id一致，如果我没有<Tosat />标签，那个小横条也是不会显示的……

我使用message并且传入一个string是可以正常显示的，但ReactNode不可以

**Comment by wegi8** [comment]
补充一下：Taro Version:3.5.5

**Comment by wegi8** [comment]
Taro并不支持直接在app.tsx中注入全局组件，所以GG
