### ISSUE TITLE
taro中使用DatetimePicker 组件，有些时候popup谈起之后，DatetimePicker组件中的cloumn为空

### ISSUE THREAD

**Issue by ananiahfox** [AntmJS/vantui#357]
**这个 Issue 涉及以下平台:**

- [ ✅] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
taro中使用DatetimePicker 组件，有些时候popup谈起之后，DatetimePicker组件中的cloumn为空
**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/41354027/192214544-5d049326-6842-4765-a9d2-cebd88f03370.png)
![image](https://user-images.githubusercontent.com/41354027/192214610-42aa48ff-ab87-4605-9822-23517c576e59.png)
![image](https://user-images.githubusercontent.com/41354027/192214761-de2c8186-3b9c-4af9-b4ed-af83ef4b68fe.png)

**环境**
微信小程序开发工具 taro3 
**附加信息**

**Comment by zuolung** [comment]
已经修复

**Comment by ananiahfox** [comment]
感谢
