### ISSUE TITLE
小程序中无法使用Dialog

### ISSUE THREAD

**Issue by Almagestum469** [AntmJS/vantui#359]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
在小程序中使用Dialog会报错
![GW~4N$V9A_ JQPV`A 3M2XI](https://user-images.githubusercontent.com/14080372/192327977-f0ccd965-d5f0-47df-9647-f6c20b852c2c.png)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by hisanshao** [comment]
这个不是Dialog的问题哦，配置应该有问题，还有之前Taro的designWidth支持函数的功能好像有点问题，不知道修复了没
