### ISSUE TITLE
vant更新版本至2.2.2后，组件样式出错

### ISSUE THREAD

**Issue by HyaCiovo** [AntmJS/vantui#363]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
更新组件库版本至2.2.2后，Cell、Radio、Cascader组件样式出错。

**复现步骤**
我在2.1.0版本引入Cascader组件时，编辑器ts报错没有导出这个组件。于是我更新了vant至最新版本，编辑器不再报错，但支付宝小程序项目中的Cell、Radio、Cascader组件样式都出现了问题，之后我降低版本到了2.2.1，样式问题不再出现，但编辑器依然报错。

**期望结果**
更新组件库版本后，组件引入不再报错，且组件样式显示正常。

**实际结果**
目前使用2.2.1版本，组件可以正常使用。但Cascader的导入编辑器会报错

**截图**

- 2.2.1版本Cell组件

<img width="288" alt="image" src="https://user-images.githubusercontent.com/88471803/192927799-7a3bcaef-88ff-4143-aaeb-7ac9c210ebb8.png">

- 2.2.2版本Cell组件

<img width="297" alt="image" src="https://user-images.githubusercontent.com/88471803/192927446-0c9d680f-8126-4d4c-af30-358db1502907.png">

- 2.2.1版本Radio组件

<img width="291" alt="image" src="https://user-images.githubusercontent.com/88471803/192927874-b2777fce-ea69-4229-a34b-79cb8e3fee6d.png">

- 2.2.2版本Radio组件

<img width="287" alt="image" src="https://user-images.githubusercontent.com/88471803/192927627-dd07b804-16a7-4440-855f-86658ad0211d.png">

- 2.2.1及以下版本，Casacder组件导入报错

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88471803/192925714-13b496ef-d74a-4ddc-8a92-6ec9c3630004.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/88471803/192926050-d0914fac-64bf-4a87-bdb4-caa18edd0cd2.png">

**环境**

**附加信息**

**Comment by hisanshao** [comment]
已修复，等下升级到2.2.3
