### ISSUE TITLE
PowerScrollView的onScrollToLower无法触发，一直呈现加载加

### ISSUE THREAD

**Issue by seanlsr** [AntmJS/vantui#365]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/34623428/193385768-728bcbdd-3bab-45db-9006-07918e64bf85.png)

**环境**
Taro 3.5.6+react18.2.0+webpack5

**附加信息**

**Comment by hisanshao** [comment]
demo没复现出来，你先用demo试试

**Comment by seanlsr** [comment]
vantui-demo，运行也是同样的问题，请排查

**Comment by yaunfei** [comment]
是的 我这边也是一直在加载

**Comment by yaunfei** [comment]
> vantui-demo，运行也是同样的问题，请排查

需要PowerScrollView设置高度，使用className设置。因为该组件使用了taro的ScrollView，这个组件需要设置高度才能触发onScrollToLower
