### ISSUE TITLE
小程序端Picker组件选中项无边框

### ISSUE THREAD

**Issue by edwards19900128** [AntmJS/vantui#366]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/11594850/194134867-d168804c-5603-4ff2-98da-c0436c8853ff.png">

**这个 Issue 涉及以下平台:**

- [x] 微信小程序

**BUG 描述**
选中项目无边框显示

**复现步骤**

**期望结果**
能有边框提示

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by hisanshao** [comment]
demo是正常的，没复现出来
