### ISSUE TITLE
建议Field输入框组件添加iconPrefix或classPrefix属性，可以自定义图标前缀

### ISSUE THREAD

**Issue by cuicuiworld** [AntmJS/vantui#371]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by zuolung** [comment]
自定义图标的可以使用renderLeftIcon
