### ISSUE TITLE
Search组件建议添加iconPrefix或classPrefix属性，可以定义图标前缀

### ISSUE THREAD

**Issue by cuicuiworld** [AntmJS/vantui#372]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**您提出的功能是否和您遇到的问题有关，请描述该问题**
目前搜索框组件 leftIcon 和 rightIcon 和 clearIcon 属性选择图标时，只能选择内置的，选不到iconfont上面的。

**您是否有建议的实现方案**
建议添加图标前缀，可以自定义图标

**其它帮助我们理解您需求的描述、截图**

**Comment by zuolung** [comment]
自定义图标可以使用renderLeftIcon
