### ISSUE TITLE
SearchBar 设置placeholderStyle无效

### ISSUE THREAD

**Issue by vaezc** [AntmJS/vantui#379]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
#488
