### ISSUE TITLE
Notify 传递参数无效

### ISSUE THREAD

**Issue by StringKe** [AntmJS/vantui#383]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
https://github.com/AntmJS/vantui/blob/main/packages/vantui/src/notify/index.tsx#L64

源代码中似乎忘了合并 porps

**复现步骤**

**期望结果**

**实际结果**

**截图**
![CleanShot 2022-10-21 at 17 27 33](https://user-images.githubusercontent.com/31089228/197162956-56aabe36-06e6-4d70-ba54-3d6a74d11083.png)
<img width="931" alt="CleanShot 2022-10-21 at 17 28 11@2x" src="https://user-images.githubusercontent.com/31089228/197163079-01c914a2-494f-4c7d-ab00-aad9943a715e.png">

**环境**

**附加信息**

**Comment by hisanshao** [comment]
复现代码发一下

**Comment by StringKe** [comment]
使用的此模板
https://github.com/AntmJS/temptaro/blob/main/src/components/container/index.tsx#L180
并修改了 container 的实现，在 180 行加入了 notify，其他文件未动。
```
    <View className={className}>
      <Notify  id='vanNotify' />
      {props.children}
    </View>
```

**Comment by zuolung** [comment]
是的不能放在container中，需要在每个页面设置唯一的id，通过selector唤起
