### ISSUE TITLE
form-item的border-bottom属性

### ISSUE THREAD

**Issue by proclml** [AntmJS/vantui#385]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
form-item组件无下边框
**复现步骤**
无
**期望结果**
form-item组件能正常显示下边框
**实际结果**

**截图**

**环境**

**附加信息**
看到`packages/vantui/src/form-item/index.less`中有这样一段样式

```less
.vant-form-formItem:last-child {
  border-bottom: none;
}
```

而一个form-item的html文件是这么写的

```tsx
<View className={`${prefixCls}-wrapper`}>
      <View className={`${prefixCls} ${prefixCls}-${layout} ${className}`}>
        (...省略)
      </View>
    </View>
```

其中，`prefixCls`变量定义为`vant-form-formItem`。按这个结构，岂不是样式中的`:last-child`永远生效？请问是故意为之还是bug？如果是故意不需要border-bottom，那么直接将样式文件中`border-bottom: @form-border-bottom;`行删除不就行了吗

**Comment by zuolung** [comment]
下边框样式已经移除，需要自己设置
