### ISSUE TITLE
Collapse组件中展开和收起没有动画效果

### ISSUE THREAD

**Issue by xuchen522178898** [AntmJS/vantui#387]
**这个 Issue 涉及以下平台:**

微信小程序

**BUG 描述**
Collapse展开收起没有动画效果，组件动画使用的是transition 但是在展开的时候 高度设置的是auto，关闭的时候高度设置的是0，由于没有设置具体数值导致没有动画效果

**复现步骤**
点击Collapse 的CollapseItem
**期望结果**
有动画效果
如果组件中无法获取有效的高度，可以提供一个配置，让使用者将高度传入
或者提供一个配置项，让可以关闭动画，否则 点击收起或者打开，会有一个动画时间的延迟
**实际结果**
无动画效果
**截图**
![image](https://user-images.githubusercontent.com/58065198/197998251-b9f08d9a-3e94-4ba6-ab0c-8b5dd6791be4.png)

**环境**

**附加信息**

**Comment by zuolung** [comment]
无法设置固定高度，动画过程的样式从高度0到初始化高度再到auto, 因为内容的高度可能不是固定的

**Comment by zuolung** [comment]
#417
