### ISSUE TITLE
CSS 变量真的支持吗？

### ISSUE THREAD

**Issue by lonyel** [AntmJS/vantui#388]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
   css 变量真的支持吗？按照文档配置，没有任何效果
**复现步骤**
  No
**期望结果**
  No
**实际结果**
No
**截图**
No
**环境**
No
**附加信息**

**Comment by boxcc** [comment]
有具体组件吗？ 我试了几个组件都OK的

**Comment by lonyel** [comment]
@boxcc 感谢你的回复。 我看了的你们的源码，确实没有看到CSS变量（不是less变量或者sass变量）（css变量类似 var(--font-size-md,@font-size-md) 之类的）应该是vant那边的saas变化这边没有同步。如果有可能，请加上这个功能，这个对于根据不同人群对UI样式（如字体、颜色等）进行动态控制至关重要。

**Comment by lonyel** [comment]
![image](https://user-images.githubusercontent.com/5528229/199245726-d93e62dc-92ab-413f-9240-f7336022b0d0.png)
这个是有赞那边的less，确实支持css变量

**Comment by boxcc** [comment]
@lonyel  这个函数做了转换  
https://github.com/AntmJS/vantui/blob/c55726f5ef6a84dc9fdb2dfc53e057adf5638e8e/packages/vantui/src/style/var.less#L716

**Comment by lonyel** [comment]
@boxcc  感谢你认真的回复。CSS变量确实是支持的。

我之前的需求是这样：希望各个用户可以自行调节字体的大小，因此希望调整如下变量达成目标：  --font-size-xs : 30px; --font-size-sm : 34px；--font-size-md : 38px;--font-size-lg : 42px;但没有效果，因此以为css变量不支持。

经过你的提醒，我在css确实找到了如这样的声明：var(--cell-font-size, 28px)，而这个样式对应的声明为：@cell-font-size: @font-size-md;  显然，转换后，基础变量@font-size-md和cell-font-size之间的联系丢失了，如果能转换成这样：var(--cell-font-size,var(--font-size-md,28px),就能保留基础原子变量对整个样式的影响力。

再次感谢。
