### ISSUE TITLE
微信小程序下所有的动画太过生硬

### ISSUE THREAD

**Issue by xiaohuwei** [AntmJS/vantui#392]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by xiaohuwei** [comment]
希望可以跟H5一样丝滑

**Comment by zuolung** [comment]
项目整体代码基本都是vant-weapp反编译过来的，部分动画代码存在缺陷，后期会优化的
