### ISSUE TITLE
Collapse CollapseItem 被点击时可能无法关闭

### ISSUE THREAD

**Issue by 1019058432** [AntmJS/vantui#403]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

**BUG 描述**
CollapseItem 被点击时可能无法关闭，或者关闭（打开）上一次点击的折叠项
**复现步骤**
重复点击某一折叠项或多个折叠项交替点击
**期望结果**
能正常关闭及展开，不会触发其它选项的展开或关闭（手风琴模式除外）
**实际结果**
CollapseItem 被点击时可能无法关闭，或者关闭（打开）上一次点击的折叠项
**截图**

**环境**
taro v3.5.1
@antmjs/vantui v2.2.8
**附加信息**

**Comment by hcw2175** [comment]
的确由此问题。官网基础例子就是这样。

具体表现：

非手风琴模式，将全部CollapseItem点击展开后，再去点击某个CollapseItem，可能无法再收起，而且永远无法全部收起。
