### ISSUE TITLE
DatetimePicker的onConfirm的结果为什么不是所选的值，总是这个控件的最小时间？

### ISSUE THREAD

**Issue by xiaoquanquanxin** [AntmJS/vantui#407]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序

**BUG 描述**
😓，无论怎么选，value字段都是这个控件展示的最小可选时间，这真的好吗？
如图

**复现步骤**
不需要复现吧，就是这样设计的吗？

**期望结果**
正常思维逻辑是我选了啥时间，value字段就是那个时间点的时间戳，而不是总是这个控件的可选时间

**实际结果**

**截图**
<img width="698" alt="截屏2022-11-20 下午7 28 46" src="https://user-images.githubusercontent.com/32757160/202899523-4d28fc1f-5aa5-414e-997b-6bc2e70a2c98.png">

**环境**

**附加信息**

**Comment by zuolung** [comment]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/28145148/202951536-4ed0b7d5-39ee-4740-bda5-0d0c1f607792.png">
发下代码，页面是否使用了Pagemeta
