### ISSUE TITLE
Toast组件在通过命令式调用时偶发不显示的问题

### ISSUE THREAD

**Issue by rambuild** [AntmJS/vantui#409]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
在小程序中，在通过Toast.success等命令式调用后，点击频率过快时，后续的Toast不会显示
**复现步骤**
在多个页面注册Toast组件并添加ID，并通过navgateTo方式跳转页面以将包含Toast组件的页面同时推入页面栈中，此时频繁快速地通过命令式调用Toast，会出现Toast不显示的问题。
**期望结果**
Toast正常显示
**实际结果**
Toast未正常显示
**截图**

**环境**
微信小程序：IOS/Android端
**附加信息**

**Comment by qingweiSun** [comment]
抖音也不显示

**Comment by zuolung** [comment]
更新到3.3.6和2.5.13
