### ISSUE TITLE
Picker on change 事件获取的值不正确

### ISSUE THREAD

**Issue by sum1201** [AntmJS/vantui#418]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/5398273/204263938-4011372b-cfdf-4dc6-819e-0bdb47c70f05.png">
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5398273/204263953-228fc39b-88f9-417b-999a-7417677e4fca.png">

- -- 图 1显示的是选择的第4列，获取的值。

- -- 图2 显示是切换第1列侯， 获取的值，此时 2，3，4列的值还是之前的值。

**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
#419 ，一个问题导致
