### ISSUE TITLE
[已找到临时解决方案] DatetimePicker在Popup里不渲染

### ISSUE THREAD

**Issue by bingtsingw** [AntmJS/vantui#425]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序

**BUG 描述**
`<Popup><DatetimePicker /></Popup>`时, 里面的内容没有渲染, 我看了下源码, 把`picker-column`里的`CustomWrapper`注释掉就可以渲染了,
但是我在vantui的demo里没有复现, 只在我自己的项目里出现这个bug, 很奇怪

**截图**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/10382462/204881294-2f56e93e-f84f-479d-9c29-86c630be89a5.png">
只在`<Popup>`里不渲染

**Comment by zuolung** [comment]
麻烦提供下taro版本

**Comment by bingtsingw** [comment]
> 麻烦提供下taro版本

3.5.7和3.5.8都不行

**Comment by bingtsingw** [comment]
https://github.com/AntmJS/vantui/commit/d45ebbd1e1bf0ca2872bed4b11f529998f86cede
我看到这个commit里面有一段改动
<img width="866" alt="image" src="https://user-images.githubusercontent.com/10382462/204953942-6132c2bb-55f3-48f0-a932-291cf91f6a77.png">
改回去好像就可以
```
{process.env.TARO_ENV === 'weapp' ? (
  <CustomWrapper>{renderColumn}</CustomWrapper>
) : (
  <View>{renderColumn}</View>
)}
```

不知道当时这段改动的用意是什么, 能不能改回去

**Comment by bingtsingw** [comment]
好像是taro编译的时候, custom-wrapper组件没有编译进去, 找到临时的解决方案了

https://github.com/NervJS/taro/issues/12239#issuecomment-1227991266

**Comment by wenlittleoil** [comment]
我也遇到了该问题，你们解决了吗，如果要在项目里面通过修改包源码来解决，那将是极其糟糕的方式，宁可弃用，也不留坑给后续维护者

**Comment by zuolung** [comment]
[3.1.4](https://github.com/AntmJS/vantui/compare/v3.1.3...v3.1.4)
