### ISSUE TITLE
_interopRequireDefault2 is not a function

### ISSUE THREAD

**Issue by brooke1220** [AntmJS/vantui#427]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

**BUG 描述**

运行之前引入没问题  如果再重新运行一下就会报错

**复现步骤**

**期望结果**

**实际结果**

**截图**

Uncaught (in promise) Error: TypeError: _interopRequireDefault2 is not a function
    at vendors-node_modules_taro_h5_prebundle_chunk-LQTHJW74_js.js:3606:27
    at Generator.throw (<anonymous>)
    at rejected (vendors-node_modules_taro_h5_prebundle_chunk-LQTHJW74_js.js:3699:48)

**环境**

**附加信息**

**Comment by louis-cai** [comment]
我也是，使用PowerScrollView q出现该问题
