### ISSUE TITLE
Bug: Search Component the focus props 

### ISSUE THREAD

**Issue by wegi8** [AntmJS/vantui#430]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
<Search focus />
绑定value时，focus总在刷新

**复现步骤**
<Search focus value={value} onChange={(e) => setValue(e.detail)} />

**期望结果**
只是mounted时候focus，或者绑定ref，可以手动focus

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by 17** [comment]
我也遇到这个问题了...  怎么解决呢

**Comment by wegi8** [comment]
I stopped using this component and used the Input of the applet itself instead.
