### ISSUE TITLE
小程序中嵌套h5，checkbox偶尔会出现样式问题

### ISSUE THREAD

**Issue by lowprofile-isp** [AntmJS/vantui#445]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

**BUG 描述**
嵌套在小程序的h5使用checkbox, 偶尔会出现样式问题，谷歌浏览器预览正常显示
**复现步骤**
在线上嵌套在小程序中的h5中，会偶尔出现样式不正常
**期望结果**
icon正常居中
**实际结果**
显示icon偏下
**截图**
![1673236736853](https://user-images.githubusercontent.com/44639576/211239010-777dafbe-c433-483a-aab9-ac8670b038ed.jpg)
**环境**
小程序h5
**附加信息**
![1673236736853](https://user-images.githubusercontent.com/44639576/211239141-ef99e467-ba8f-4df9-8b3e-11146e7f985a.jpg)

**Comment by zuolung** [comment]
没有复先，可以确认下真机是否会有问题吗？有可能是构建配置问题

**Comment by Lccitem** [comment]
就是真机会出现，浏览器跟微信开发者工具都没复现，真机有时是好的 切一切页面就有问题了
