### ISSUE TITLE
在From中使用CheckboxGroup无法选中，控制台报错

### ISSUE THREAD

**Issue by ananiahfox** [AntmJS/vantui#448]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
在From中使用CheckboxGroup无法选中，控制台报错
![image](https://user-images.githubusercontent.com/41354027/212862153-e18c034d-3ce0-4b76-a205-7733848275df.png)

**复现步骤**
![image](https://user-images.githubusercontent.com/41354027/212862415-3d892aa7-f14d-472d-88ba-b36ff90ad60e.png)

**期望结果**
可以选中
**实际结果**
无法选中
**截图**

**环境**

**附加信息**
谢谢

**Comment by zuolung** [comment]
![image](https://user-images.githubusercontent.com/28145148/215309953-af9f784f-854c-4d55-ad44-2cbf85b51dba.png)

**Comment by zuolung** [comment]
可能是你initialValues初始化数据不是数组，或者你检查下vantui版本是否需要更新
