### ISSUE TITLE
deviceRatio 配置中不存在 function designWidth(input) {      ...的设置！

### ISSUE THREAD

**Issue by chengluliu** [AntmJS/vantui#449]
**这个 Issue 涉及以下平台:**

- [X] 微信小程序
 
**BUG 描述**

deviceRatio 配置中不存在 function designWidth(input) {
        if (input.file.replace(/\\+/g, "/").indexOf("@antmjs/vantui") > -1) {
            return 750;
        }
        return 375;
    } 的设置！

**复现步骤**
git@github.com:chengluliu/NutUIDemo.git

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by boiboif** [comment]
怎么解决的啊 我降级taro版本也遇到了
