### ISSUE TITLE
(L.current[e] || {}).getCurrentIndex is not a function

### ISSUE THREAD

**Issue by oydiligent** [AntmJS/vantui#451]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序

**BUG 描述** 
微信开发后台显示 这个bug，问题集中的系统类型为Android，本地开发工具没有
**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/19690319/215980496-469bbc78-a591-4a21-987b-6fef9d0cd580.png)

**环境**

**附加信息**

**Comment by oydiligent** [comment]
> 机型和vantui版本

问题日志是从微信后台获取到的，vantui版本2.4.0
![image](https://user-images.githubusercontent.com/19690319/216214315-1ebfd82d-3e02-4161-a93e-087c5569e806.png)

**Comment by zuolung** [comment]
测试了几部低版本的手机，未复现问题，可以给下你报错的代码吗？还有taro的版本

**Comment by oydiligent** [comment]
> 

因为属于线上出错，错误率在8%左右，微信日志查看到的问题，使用的代码如下，简单的Popup组件封装一个Picker，taro版本3.5.7
![image](https://user-images.githubusercontent.com/19690319/217777994-d4686279-348c-4846-bd0b-e2721749bafe.png)
