### ISSUE TITLE
PowerScrollView组件下拉刷新很卡

### ISSUE THREAD

**Issue by boiboif** [AntmJS/vantui#455]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
下拉刷新过程卡顿

**环境**
手机型号红米K50

**Comment by 17** [comment]
部分安卓发现有一样问题，还有下拉刷新有一定情况下不能下拉（苹果13也会）。
