### ISSUE TITLE
PowerScrollView上拉，无法加载更多数据

### ISSUE THREAD

**Issue by seanlsr** [AntmJS/vantui#456]
**这个 Issue 涉及以下平台:**

- [x ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/34623428/217523214-8cb4f408-de3a-42b6-af99-e4ce34aa1860.png)
![ae885b6659419d1d9bf3ed46b64e234](https://user-images.githubusercontent.com/34623428/217523269-8ab982d0-a3f6-4413-8cda-a768441c56ad.jpg)

**环境**
taro 3.5.12 + vantui2.5.0
**附加信息**
官方小程序示例也同样是一直显示“加载中...”

**Comment by boiboif** [comment]
官方例子并不会呀

**Comment by zuolung** [comment]
可以给下代码吗

**Comment by yujunfan** [comment]
设置下PowerScrollView的高度

**Comment by seanlsr** [comment]
> 设置下PowerScrollView的高度

确实，微信小程序也要设置一个高度才能正常
