### ISSUE TITLE
formItem的输入框内就会变成[object Promise] （开发工具偶现）

### ISSUE THREAD

**Issue by zhengzhou** [AntmJS/vantui#459]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

表单输入框会出现  [object promise] 字符

代码如下
```
  <FormItem
                label="姓名"
                name="nickname"
                trigger="onInput"
                valueFormat={(e) => e.detail.value}
              >
      <Input placeholder="请输入姓名" maxlength={10} />
</FormItem>
```

**复现步骤**

在输入框位置快速输入数字或者字母，输入框内就会闪现[object promise] 字符, 有时候会直接替换掉现有的输入内容。
切换英文字符或者数字键盘快速输入更容易出现。

**期望结果**

正常输入

**实际结果**

出现异常自负

**截图**

![](http://h5.qihuaitech.com/files/Snipaste_2023-02-14_19-07-18.png)

**环境**

taro 3.6.0
@antmjs/vantui@2.5.1

**附加信息**

https://github.com/AntmJS/vantui/blob/ea73916469d3dd24356de31e2e34f83ba8fda455/packages/vantui/src/form-item/index.tsx#L91

微信onInput属性好像不能设置成async的方法

**Comment by zuolung** [comment]
可能是由于微信任务队列处理时内存不足导致，之前偶现过，重启开发工具就好了，后续会将异步方式剥离出来

组件库最好基于taro版本3.5.7使用

**Comment by zhengzhou** [comment]
不是只有开发工具会这样呢，是真机正式环境，几乎所有form输入都会出现，概率还是9成以上, 确实是3.5.7升级3.6之后出现的，大面积输入框不可用

**Comment by StephenCMZ** [comment]
search 组件也存在同样的问题，快速输入会直接替换掉现有的输入内容

**Comment by chj-damon** [comment]
@zuolung 为什么关掉？现在还是会有这个问题

**Comment by ziqiya** [comment]
这个PR #491 修复了，如果可以的话麻烦 approve 一下

**Comment by zuolung** [comment]
validateTrigger也为onInput的时候时候会有问题
