### ISSUE TITLE
bug: radio组件配合cellgroup，使用renderRight不显示radio

### ISSUE THREAD

**Issue by jhxxs** [AntmJS/vantui#46]
![Snipaste_2021-11-08_10-33-05](https://user-images.githubusercontent.com/7448223/140677079-6e948bb3-1946-43ff-a815-ab7a97c237a6.png)

项目使用的是`taro`+`ts`+`taro-hook`，按照文档提供的demo，使用`renderRight`，`cell`里不显示`radio`组件，换用`renderRightIcon`可以显示，但是没有选中效果，而且点击事件`dataset`为空。

[复现repo](https://github.com/jhxxs/vantui)

**Comment by hisanshao** [comment]
好的，我们看下

**Comment by Chitanda60** [comment]
@jhxxs 直接传name到onClick里使用，demo为了跟vant的保持一致在调用时做了dataset的封装；没有renderRight，只有renderIcon

**Comment by jhxxs** [comment]
> @jhxxs 直接传name到onClick里使用，demo为了跟vant的保持一致在调用时做了dataset的封装；没有renderRight，只有renderIcon，文档我们会改下

不过radio的选中效果还是没有

**Comment by Chitanda60** [comment]
> > @jhxxs 直接传name到onClick里使用，demo为了跟vant的保持一致在调用时做了dataset的封装；没有renderRight，只有renderIcon，文档我们会改下
> 
> 不过radio的选中效果还是没有

可以先参考下packages/vantui-demo/src/pages/radio的写法，下一版本会修复。
