### ISSUE TITLE
支付宝小程序FormItem报错

### ISSUE THREAD

**Issue by loethen** [AntmJS/vantui#460]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
页面中使用FormItem报错
**复现步骤**
`import { Form,Button, Rate, FormItem } from '@antmjs/vantui'
`

`<FormItem label="评价">
                <Rate color="#ffd21e" />
            </FormItem>`
**期望结果**
正常使用
**实际结果**
页面编译不了
`TypeError: Function(...) is not a function
`
**截图**
![Screenshot 2023-02-20 at 14 18 05](https://user-images.githubusercontent.com/291151/220026419-8aef6c52-315f-4fc1-866e-453b20961dcb.png)

**环境**
taro3.6
vantui2.5.0
**附加信息**
taro3.5.7也是一样的错误
Tab组件也是一样的问题

**Comment by zuolung** [comment]
3.5.7这边是好的，taro3.5.7后需要重启服务，3.6版本可能还存在潜在问题晚点再升级

**Comment by zuolung** [comment]
([chore: swc替换babel](https://github.com/AntmJS/vantui/commit/7064b8339c902ed5d8c8089cf1b7c3fc62c22e70)), 修复了这个错误， 待发布

**Comment by adufeng** [comment]
> 

还有tab,tabs组件在支付宝中也报这个错

**Comment by adufeng** [comment]
> ([chore: swc替换babel](https://github.com/AntmJS/vantui/commit/7064b8339c902ed5d8c8089cf1b7c3fc62c22e70)), 修复了这个错误， 待发布

还有tab,tabs组件在支付宝中也报这个错
<img width="374" alt="image" src="https://user-images.githubusercontent.com/52154350/220811282-b747048e-08c6-4d6a-a6f1-8043245cda46.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/52154350/220811293-c3c7c014-4abf-45e2-8c47-6f1f09b7d98d.png">
