### ISSUE TITLE
微信端search 组件快速输入会直接替换掉现有的输入内容

### ISSUE THREAD

**Issue by zuolung** [AntmJS/vantui#464]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

**复现步骤**
search 组件快速输入会直接替换掉现有的输入内容
**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by StephenCMZ** [comment]
遇到同样的问题，我的情况是由于页面**列表数据太多**导致的，解决的办法是列表改用 VirtualList 组件。
