### ISSUE TITLE
Calender

### ISSUE THREAD

**Issue by mengayng** [AntmJS/vantui#465]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
calender组件如果设置了底部导航栏，下边的确认按钮会被苹果底部导航栏挡住
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
开启safeAreaInsetBottom
