### ISSUE TITLE
Collapse 手风琴模式 Bug

### ISSUE THREAD

**Issue by TaroXin** [AntmJS/vantui#468]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

正常设定手风琴模式，设置初始展开数组，点击第二个的时候，第一个出现无法收起的问题，必须手动点击之后才会正常

**复现步骤**

```tsx
import { Collapse, CollapseItem } from '@antmjs/vantui'
import { useState } from 'react'

import './index.less'

export default function CollapseModule() {
  const [checked, setChecked] = useState(['1'])

  return (
    <Collapse accordion className='collapse-module-container' value={checked} onChange={e => setChecked(e.detail)}>
      <CollapseItem title='合计' name='1'>
        内容区域
      </CollapseItem>
      <CollapseItem title='测试属性' name='2'>
        内容区域
      </CollapseItem>
      <CollapseItem title='测试内容' name='3'>
        内容区域
      </CollapseItem>
    </Collapse>
  )
}

```

**期望结果**

可以正常操作

**实际结果**

**截图**

GIF 图如下 👇🏻

![未命名](https://user-images.githubusercontent.com/19855713/222873411-ab972d2d-68a3-4fdc-89ae-9393bc27d3ea.gif)

**环境**

**附加信息**

**Comment by TaroXin** [comment]
官网的手风琴演示也有此Bug 

https://antmjs.github.io/vantui/#/collapse?target=%E6%89%8B%E9%A3%8E%E7%90%B4

**Comment by zuolung** [comment]
感谢反馈🙏，后续会修复，你可以先设置初始化没有默认展开

**Comment by LarsAlexand** [comment]
还没有修复吗🤕
