### ISSUE TITLE
CollapseItem name 值类型为 number 的时候无法正常开启

### ISSUE THREAD

**Issue by TaroXin** [AntmJS/vantui#473]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
设置 CollapseItem 的 name 为数字，Collapse 组件无法正常开启

而且未设置手风琴，但是好像变成了手风琴模式！

**复现步骤**

```jsx
<Collapse value={checked} onChange={openCollapse}>
    <CollapseItem
        name={1234}
      >
        <View className='collapse-module-section'>
          TEST_NAME
        </View>
      </CollapseItem>
      <CollapseItem
        name={4567}
      >
        <View className='collapse-module-section'>
          TEST_NAME
        </View>
      </CollapseItem>
</Collapse>
```

**期望结果**

**实际结果**

**截图**

GIF 👇🏻

![未命名](https://user-images.githubusercontent.com/19855713/224480809-47a1d9c9-5a25-419e-8665-3568bc0b034a.gif)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
使用字符串试试
