### ISSUE TITLE
 Field组件修改不了placeholder的样式，placeholderClass设置了但最终会被替换成van-field__placeholder

### ISSUE THREAD

**Issue by a869057476** [AntmJS/vantui#474]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [X] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
 支付宝小程序（其他平台未验证），Field组件修改不了placeholder的样式，placeholderClass设置了但最终会被替换成van-field__placeholder
**复现步骤**

**期望结果**

**实际结果**

**截图**
![8139aaf5fd617c9592688eb4897809c](https://user-images.githubusercontent.com/20514461/224915850-866f5012-8658-4382-a45f-f7d6a0d70504.png)
![83977233b736e909fb09951bbda8eec](https://user-images.githubusercontent.com/20514461/224915870-82c01dce-1479-4d7c-8395-4079f021fd69.png)

**环境**

**附加信息**

**Comment by hisanshao** [comment]
placeholderClass没有用到，下个版本加，可以先用placeholderStyle实现
