### ISSUE TITLE
Unite 组件在最新版本中消失了

### ISSUE THREAD

**Issue by Moonisky** [AntmJS/vantui#475]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**您提出的功能是否和您遇到的问题有关，请描述该问题**

我看到官网上有一个 Unite 高级模版，但是在 VantUI 最新的版本中没有找到这个组件，查了一下在这个[提交](https://github.com/AntmJS/vantui/commit/5cef4a89ad11bb56252771e067e45ff6433cc628)中 Unite 组件被移除了，请问是因为有什么潜在问题吗？

感谢您的回复。

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
单独铃出来了@antmjs/unite
