### ISSUE TITLE
生产环境引用 power-scroll-view 组件大量 "null is not an object (evaluating \'t.scrollTop\')" 错误。

### ISSUE THREAD

**Issue by 17** [AntmJS/vantui#476]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
在腾讯 we 统计中 [JS分析/错误内容详情](https://wedata.weixin.qq.com/mp2/js-error-detail) 中可以查看到，
引用 `power-scroll-view` 组件的页面有大量 `null is not an object (evaluating \'t.scrollTop\')` 错误。
在我们业务代码并无引用 `scrollTop` 。一番追查发现应是 [power-scroll-view/index.tsx#L168](https://github.com/AntmJS/vantui/blob/5e64f07eaad46ce9f2bcbf7369391472db9b419a/packages/vantui/src/power-scroll-view/index.tsx#L168) 引用发生错误。

并且下拉刷新功能大部分时候是不能使用的。

**附加信息**
```
null is not an object (evaluating \'t.scrollTop\')
@https://usr//app-service.js:16218:41
p@https://usr//app-service.js:20021:24
@https://usr//app-service.js:20119:22
r@https://usr//app-service.js:20405:21
u@https://usr//app-service.js:20422:14
@https://lib/WASubContext.js:1:51594
n@https://lib/WASubContext.js:1:27961
@https://lib/WASubContext.js:1:38413
E@https://lib/WASubContext.js:1:38145
@https://lib/WASubContext.js:1:38183
f@https://lib/WASubContext.js:1:136815
@https://lib/WASubContext.js:1:103001
@https://lib/WASubContext.js:1:132284
p@https://lib/WAServiceMainContext.js:1:136557
@https://lib/WAServiceMainContext.js:1:124786
```
![image](https://user-images.githubusercontent.com/6132593/225541822-c4d9df63-d515-40fe-8531-500e4272138f.png)

**Comment by hisanshao** [comment]
只能catch一下了，下个版本判断一下
