### ISSUE TITLE
Formitem设置label 显示应该输入reactnode 但是内容为icon不显示

### ISSUE THREAD

**Issue by gangxinhui** [AntmJS/vantui#494]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Formitem设置label 显示应该输入reactnode 但是内容为icon不显示

**复现步骤**

**期望结果**

**实际结果**

**截图**
<img width="806" alt="image" src="https://user-images.githubusercontent.com/72453735/233769786-b9d5a87a-4c59-4a37-a55a-735c52e8fa94.png">
<img width="337" alt="image" src="https://user-images.githubusercontent.com/72453735/233769808-2fc759cf-86e5-45e5-91fb-fe95464a99b0.png">

**环境**

**附加信息**

**Comment by zuolung** [comment]
查看下<icon />其他地方能否渲染，或者升级下vantui的版本

**Comment by boxcc** [comment]
应该是Taro的机制问题，要传reactNode都要render开头才行， 截图里的renderRight就是这种规范
