### ISSUE TITLE
resolve '@antmjs/vantui/es/index-list/style' in '/Users/daijianjiang/Desktop/gym-one-client/src/pages/Index/CitySelect'   Parsed request is a module

### ISSUE THREAD

**Issue by AaronDaiR** [AntmJS/vantui#499]
**这个 Issue 涉及以下平台:**

- [√] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [√ ] Web 平台（H5）

**BUG 描述**
Taro 3.6.5 安装 @antmjs/vantui 正常引入 报错

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by AaronDaiR** [comment]
![image](https://user-images.githubusercontent.com/53423109/234794952-45958e39-d36c-4c1d-8c83-222a7577f8a5.png)

**Comment by zuolung** [comment]
index-list这个组件哪里引用的啊？，建议去lib下面引用全部样式

**Comment by zuolung** [comment]
组件所在父元素需要设置高度

**Comment by AaronDaiR** [comment]
> 组件所在父元素需要设置高度

设置过了，往下滑动标题粘性置顶失效了，右侧索引栏点击也失效。 请 @zuolung 明鉴，冤啊

**Comment by zuolung** [comment]
希望提供下复现仓库
