### ISSUE TITLE
Icon图标变小，设置size无效

### ISSUE THREAD

**Issue by seanlsr** [AntmJS/vantui#501]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x ] Web 平台（H5）

**BUG 描述**
Icon图标变小，设置size无效

**复现步骤**

**期望结果**

**实际结果**

**截图**
![微信截图_20230503161905](https://user-images.githubusercontent.com/34623428/235865040-8ee651f3-e2f4-4ce4-bec7-e49494b1596c.png)

**环境**
vantui 2.5.6
taro 3.6.5
**附加信息**

**Comment by zuolung** [comment]
参考下官方模板的配置
