### ISSUE TITLE
Calendar如何自定义当前日期的样式？

### ISSUE THREAD

**Issue by chenzhengWin** [AntmJS/vantui#510]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [x] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**有这样的需求：当前日期用A样式，选中日期用B样式。**
假设我们现在要做当前日期（今日）样式为蓝色字体，如何设置呢？
目前只找到了设置选定日期的方法，我重写了 selected-day 的样式

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

<img width="375" alt="image" src="https://github.com/AntmJS/vantui/assets/48211880/55c22741-f682-4145-8671-0fb1c4728639">

**Comment by zuolung** [comment]
defaultDate

**Comment by zuolung** [comment]
样式覆盖下

**Comment by chenzhengWin** [comment]
> 

你怎么覆盖？至少要找到代表当日的class

**Comment by chenzhengWin** [comment]
> 样式覆盖下
你怎么覆盖？至少要找到代表当日的class，目前是官方没提供

**Comment by zuolung** [comment]
使用`color`
