### ISSUE TITLE
VirtualList + InfiniteScroll 会导致卡死，还挺频繁的

### ISSUE THREAD

**Issue by diamont1001** [AntmJS/vantui#518]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

长列表导致小程序卡死，footer 显示 “没有更多了”，但是是显示在列表的中间的。

<img width="380" alt="image" src="https://github.com/AntmJS/vantui/assets/7159888/b63a1905-51e8-4a09-a325-b0041ef84f89">

而列表底部显示 2N 个列表元素，footer 则在长列表的中间位置大概是离顶部 2N 个元素的下面。

**复现步骤**

参考官方文档上的 VirtualList + InfiniteScroll 实现的长列表，向下滚动会导致各个小程序卡死，几乎每次都能触发，具体原因还定位中。

初步排除 InfiniteScroll 的问题，目前在排查 VirtualList。

**期望结果**

**实际结果**

**截图**

**环境**

- "@tarojs/taro": "3.6.7",
- "@antmjs/vantui": "3.0.2"

**附加信息**

**Comment by zuolung** [comment]
taro3.6x某几个版本会有问题

**Comment by diamont1001** [comment]
目前使用的Taro是最新的 3.6.7

**Comment by zuolung** [comment]
已解决

**Comment by imitator2020** [comment]
> 已解决
请问解决办法是怎样的呢，这边也遇到了
"@tarojs/taro": "3.6.5"
"@antmjs/vantui": "3.2.1",
