### ISSUE TITLE
InfiniteScroll组建的 ref 上没有reset()方法 

### ISSUE THREAD

**Issue by ananiahfox** [AntmJS/vantui#519]
**这个 Issue 涉及以下平台:**

- [✓] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [] Web 平台（H5）

**BUG 描述**
InfiniteScroll组建的 ref 上没有reset()方法 
reset is not a function
**复现步骤**
infiniteScrollInstance?.current?.reset();
**期望结果**
没有就不要在文档上写 
**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
应该是使用时机问题

**Comment by ananiahfox** [comment]
感谢回复 我再找找原因
