### ISSUE TITLE
小程序端带输入框的Dialog弹出框显示异常 

### ISSUE THREAD

**Issue by Damoness** [AntmJS/vantui#537]
**这个 Issue 涉及以下平台:**

- [x ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
小程序端带输入框的Dialog弹出框显示异常 
**复现步骤**

打开官方小程序demo=>反馈组件=>Dialog弹出框=>确认弹框

![IMG_8828](https://github.com/AntmJS/vantui/assets/5622121/907748db-0137-4f64-9a95-111f7d198972)
输入框没有正常显示

相关代码
```
 Dialog_.confirm({
      title: '标题',
      message: (
        <Input
          placeholder="请输入内容"
          value={value}
          onInput={(e) => setValue(e.detail.value)}
        />
      ),
    })
```

H5端显示没有问题
<img width="355" alt="image" src="https://github.com/AntmJS/vantui/assets/5622121/a4a787ac-2731-4136-aeed-d4fb211303a5">
https://antmjs.github.io/vantui/main/#/dialog

**期望结果**

<img width="355" alt="image" src="https://github.com/AntmJS/vantui/assets/5622121/a4a787ac-2731-4136-aeed-d4fb211303a5">

**实际结果**
![IMG_8828](https://github.com/AntmJS/vantui/assets/5622121/907748db-0137-4f64-9a95-111f7d198972)
**截图**

**环境**

**附加信息**

**Comment by chunbaiseakuang** [comment]
Dialog_.confirm调用，message传入ReactNode类型，源码里面却用Text标签承载，就会产生这个bug

**Comment by Damoness** [comment]
> 



> Dialog_.confirm调用，message传入ReactNode类型，源码里面却用Text标签承载，就会产生这个bug

我也发现了这个问题

**Comment by zuolung** [comment]
已修复
