### ISSUE TITLE
From 表单使用initalValues 初始化字段 值为0时，不渲染

### ISSUE THREAD

**Issue by liangzai006** [AntmJS/vantui#541]
**这个 Issue 涉及以下平台:**

- [X] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Form 表单 使用initialValues初始化字段，只要字段预设值为0，就不会渲染
**复现步骤**
字段设置为0，     status: 1,
                examStatus: 0,
                payRoll: 0
**期望结果**

**实际结果**

**截图**
<img width="379" alt="image" src="https://github.com/AntmJS/vantui/assets/46879761/05fc69f5-f1f4-4472-8a1c-9e15e2306be7">
<img width="383" alt="image" src="https://github.com/AntmJS/vantui/assets/46879761/9fd1838a-1fed-40be-b63d-db9d065154b9">

**环境**

**附加信息**

**Comment by zuolung** [comment]
具体怎么设置的，是自定义的组件吗

**Comment by liangzai006** [comment]
> 具体怎么设置的，是自定义的组件吗

在Form 组件上添加
![image](https://github.com/AntmJS/vantui/assets/46879761/02a82eb4-377b-42e5-96ec-ba00bbcea716)， 组件是使用的 ActionSheet ， 和VIew
