### ISSUE TITLE
scrollview中使用Popup包裹Picker组件，列没有渲染，在scrollview之外可以

### ISSUE THREAD

**Issue by xiaoshuimao** [AntmJS/vantui#547]
**这个 Issue 涉及以下平台:**

- 微信小程序

**BUG 描述**
类似这个去掉customWrapper是可以的。
#425 
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by w567675** [comment]
试了下scrollView中 不用Popup包裹Picker，Picker也是正常

**Comment by liudichen** [comment]
我实际使用时在Popup或CollapseItem父组件下，再次用Popup包裹Picker/Calendar均会导致Picker/Calendar无法正确渲染。。。
