### ISSUE TITLE
ScrollView中使用Popup会随着滚动

### ISSUE THREAD

**Issue by xiaoshuimao** [AntmJS/vantui#548]
**这个 Issue 涉及以下平台:**

-  微信小程序
-  支付宝小程序

**BUG 描述**

**复现步骤**

**期望结果**
请问下，是不是加一个root-portal （https://developers.weixin.qq.com/miniprogram/dev/component/root-portal.html）
处理会没有这个的问题？
**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
放外面使用
