### ISSUE TITLE
一点建议，3个bug

### ISSUE THREAD

**Issue by luyang12138** [AntmJS/vantui#55]
**建议：**
1. 希望支持按需引入，不然打包体积过大
**发现的bug：**
1. 细边框button无下划线（微信小程序demo）
2. 在页面根节点不设置width:100%的情况下，页面会overflow。根节点加上width:100%就显示正常。（微信小程序自己引入的时候）
3. 源码中部分地方是引入'js文件，而实际源码中是引入ts文件'。（不影响使用，看源码时候发现）

感谢作者的开源！

**Comment by Chitanda60** [comment]
@luyang12138 按需引入正在跟进，请问3是什么意思，方便的话能提供个代码片段？

**Comment by luyang12138** [comment]
![QQ截图20211110204019](https://user-images.githubusercontent.com/31301884/141114996-5e7860d4-fe4d-4467-ae73-9f4f4e2aa509.jpg)

**Comment by h2570206577** [comment]
目前我是把整个UI组件库下载下来，放在项目里面，自己按需引入，可以参考一下
