### ISSUE TITLE
3.1.3 Rate组件allowHalf=true时显示异常

### ISSUE THREAD

**Issue by liudichen** [AntmJS/vantui#550]
**这个 Issue 涉及以下平台:**

- [x ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
version3.1.3中Rate组件 在allowHalf=true时数量显示不正常
回退到3.1.2或之前就恢复正常了。我重新安装了几次总是这样，不清楚是否是个例

**复现步骤**
@3.1.3
```
<View>
 <View>
        <Rate value={1} count={2} allowHalf />
      </View>
      <View>
        <Rate value={1}  allowHalf />
      </View>
      <View>
        <Rate value={1}  />
      </View>
</View>
```

**期望结果**
数量显示正常
**实际结果**
数量是2倍，而且显示样式也不正确
**截图**
![image](https://github.com/AntmJS/vantui/assets/45782636/3e9b7726-bf7c-4345-a3fc-fc2645bd94fe)

**环境**
```
"@antmjs/vantui": "^3.1.3",
 "@tarojs/components": "3.6.8",
 "@tarojs/helper": "3.6.8",
```
**附加信息**

**Comment by zuolung** [comment]
肯能是taro配置问题
