### ISSUE TITLE
使用瀑布流组件，打包失败

### ISSUE THREAD

**Issue by adufeng** [AntmJS/vantui#554]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
NODE_ENV=production 打包报错
Error: Cannot get final name for export 'useForceUpdate' of ./node_modules/@antmjs/vantui/es/waterfall-flow/hooks/index.js

**复现步骤**

**期望结果**

**实际结果**

**截图**
<img width="1109" alt="image" src="https://github.com/AntmJS/vantui/assets/52154350/1c1a320a-08a2-488a-843c-30fcfb4387d6">

**环境**

**附加信息**

**Comment by 751848178** [comment]
没能复现，可以的话提供提供一下最小复现仓库吧
