### ISSUE TITLE
h5

### ISSUE THREAD

**Issue by locdlocd** [AntmJS/vantui#555]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [x] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by locdlocd** [comment]
不管是引用组件 还是按钮  字体都偏大  我看了一下  页面上读取@antmjs/vantui/es/style/base.less文件中的 font-size是28px

**Comment by locdlocd** [comment]
这个要怎么处理

**Comment by zuolung** [comment]
https://antmjs.github.io/vantui/main/#quickstart?target=%E5%85%BC%E5%AE%B9%20Vant%20Weapp%20%E4%BB%A5%E5%8F%8A%20%E5%85%BC%E5%AE%B9%E9%A1%B9
