### ISSUE TITLE
Field  为 textarea 禁用 且 value 不存在的时候，会显示 a

### ISSUE THREAD

**Issue by pigjs** [AntmJS/vantui#557]
**这个 Issue 涉及以下平台:**

- [✅] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Field  为 textarea 禁用 且 value 不存在的时候，会显示 a

**复现步骤**
<Field value='' type='textarea' disabled />
![截屏2023-08-18 下午4 51 40](https://github.com/AntmJS/vantui/assets/50874111/6f8e8a00-8265-4988-9753-2d60f25d1439)

**期望结果**
期望value不存在的时候不显示内容
**实际结果**
显示了一个 a
**截图**
![截屏2023-08-18 下午4 50 54](https://github.com/AntmJS/vantui/assets/50874111/212814bf-9aa1-4cbc-a1a8-53189bf9ca14)

**环境**
微信小程序
**附加信息**

**Comment by zuolung** [comment]
升级下版本
