### ISSUE TITLE
通过createOnlyDialog创建的Dialog无法打开

### ISSUE THREAD

**Issue by ChiaJune** [AntmJS/vantui#561]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

使用 `createOnlyDialog` 创建的 `Dialog`，如果在 `Popup` 打开后调用 `Dialog.confirm` 或者 `Dialog.alert` 无法打开 `Dialog`，通过组件的形式打开没问题

**复现步骤**

`Dialog` 和 `Popup` 在同一层或者 `Dialog` 在 `Popup` 内部调用 `Dialog.confirm` 或者 `Dialog.alert`

**期望结果**

`Dialog` 能正常打开

**实际结果**

`Dialog` 无法打开

**截图**

**环境**

- `@antmjs/vantui: ^3.1.5`
- `taro: 3.6.13`

**附加信息**

**Comment by yurnery** [comment]
我试了半天, 也发现什么反应都没有

**Comment by yurnery** [comment]
需要 render 这个 `<Dialog_ />` 才可以使用命令式 API

**Comment by ChiaJune** [comment]
> 需要 render 这个 `<Dialog_ />` 才可以使用命令式 API

肯定是 render 了的。`<Dialog_ />` 和 `Popup` 同级或者 `<Dialog_ />` 在 `Popup` 内部都不行

**Comment by leejunhui** [comment]
@ChiaJune 你好，我也遇到和你一样的问题了，请问最后解决了吗?

**Comment by ChiaJune** [comment]
> @ChiaJune 你好，我也遇到和你一样的问题了，请问最后解决了吗?

通过state去控制show，不用createOnlyDialog这个函数来打开

**Comment by leejunhui** [comment]
@ChiaJune +1，我最后也没有用 createOnlyDialog 函数
