### ISSUE TITLE
疑问：form的rule为什么必须要有值才运行？

### ISSUE THREAD

**Issue by boxcc** [AntmJS/vantui#572]
代码： https://github.com/AntmJS/vantui/blob/4e7ac34cdcb3467cfd565be9e11c7d61dec2e73a/packages/vantui/src/form/core/formstore.ts#L382-L399

我发现rule只有在有值才会触发，是有什么特殊原因吗？

**Comment by zuolung** [comment]
required已经判断了必填, 布尔类型的后期会兼容下
