### ISSUE TITLE
PullToRefresh和InfiniteScroll一起使用，数据量少的时候，loadMore的状态一直处于loading状态

### ISSUE THREAD

**Issue by GetWebHB** [AntmJS/vantui#579]
**这个 Issue 涉及以下平台:**

- [*] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
数据量较少的时候，InfiniteScroll一直处于loading状态，loadMore函数没有触发

**复现步骤**
https://antmjs.github.io/vantui/main/#/infinite-scroll 基本使用案例修改返回的数据量
<img width="736" alt="image" src="https://github.com/AntmJS/vantui/assets/49827327/76f998b1-98ed-42f3-b6a5-0f4744491470">
<img width="608" alt="image" src="https://github.com/AntmJS/vantui/assets/49827327/b318c17f-d9df-4b0a-b600-caa724f69a74">

**期望结果**

**实际结果**

**截图**
<img width="373" alt="image" src="https://github.com/AntmJS/vantui/assets/49827327/e37f832a-50ad-4ca3-b012-bdb42bea13b6">

**环境**

**附加信息**

**Comment by GetWebHB** [comment]
两周没人回复 Issue...

**Comment by zuolung** [comment]
判端下数据总列表长度是否大于一页的长度`  if(data.length > 10) InfiniteScrollInstance.current?.reset()`
```tsx
  const loadMore: InfiniteScrollProps['loadMore'] = async () => {
    return new Promise(async (resolve) => {
      const reslult = await mockGoods()
      const newData = data.concat(reslult)
      setdata(newData)
      // 以下是简单的模拟请求，正常请求请按条件执行`resolve('complete')`
      resolve(newData.length >= 10 ? 'complete' : 'loading')
    })
  }

  const onRefresh: IPullToRefreshProps['onRefresh'] = () => {
    return new Promise(async (resolve) => {
      const reslult = await mockGoods()
      setdata(reslult)
      if(data.length > 10) InfiniteScrollInstance.current?.reset()
      resolve(undefined)
    })
  }
```

**Comment by GetWebHB** [comment]
非常感谢～
