### ISSUE TITLE
<Switch /> 组件变量问题

### ISSUE THREAD

**Issue by bingtsingw** [AntmJS/vantui#580]
`--switch-on-background-color` 似乎没有生效，不仅默认的`@primary-color;`不生效，在`provider`里设置其他值也不行；

另外`size`似乎没有变量设置，只能通过传值`size`的方式，默认`60`实在是太大了

**Comment by hcw2175** [comment]
@zuolung 升级 3.2.2 变量 size 设置无效，只能通过 css 变量控制。
<img width="1087" alt="image" src="https://github.com/AntmJS/vantui/assets/8132286/e42bed84-fc5b-4a72-adf7-54b29adc4524">
