### ISSUE TITLE
Tabs 在taro3.4.12中选中底部高亮点不显示

### ISSUE THREAD

**Issue by xiao252** [AntmJS/vantui#590]
**这个 Issue 涉及以下平台:**

- [x ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
![image](https://github.com/AntmJS/vantui/assets/32588856/06755576-1083-4a11-b11e-a3e3db0a82ff)
![image](https://github.com/AntmJS/vantui/assets/32588856/8d352b62-5e97-4568-9b8a-d518f216ca29)
![image](https://github.com/AntmJS/vantui/assets/32588856/0184fd4c-6a16-4f15-9a8d-d85e384af4e2)

示例h5版本是有的，微信小程序不显示
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
#601
