### ISSUE TITLE
Toast_ 在组件重渲染时无法正常显示

### ISSUE THREAD

**Issue by ImpTyrion** [AntmJS/vantui#598]
![image](https://github.com/AntmJS/vantui/assets/76657138/58511927-f998-464c-97f5-412535e50357)
请问是用法不对，还是什么问题，谢谢！

**Comment by JimWang-happy** [comment]
![image](https://github.com/AntmJS/vantui/assets/76657138/ce68950d-f9ed-4cf0-9fa2-31772dff6179)
A 页面写了 Dialog_(组件里写了 <Dialog_ />)，第一次可以正常弹出，跳转到 B 页面后，再navigateBack 回到 A页面后，Dialog_无法正常弹出

**Comment by shenjo** [comment]
+1 ,延迟等组件渲染完之后可以成功。。。

**Comment by json-q** [comment]
Toast我这里是可以正常生效的，但Dialog不行。Dialog那种有什么解决方法吗？我加了延迟也不行

**Comment by zuolung** [comment]
#635
