### ISSUE TITLE
Tabs active动态改变van-tabs__line会有bug

### ISSUE THREAD

**Issue by GetWebHB** [AntmJS/vantui#601]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
同：https://github.com/AntmJS/vantui/issues/596

**复现步骤**
```tsx
function DemoBar() {
  const [active, setActive] = useState('a')

  useEffect(() => {
    setTimeout(() => {
      setActive('c')
    }, 500)
  }, [])

  return (
    <Tabs active={active}>
      <Tab title="a" name="a">
        内容 1
      </Tab>
      <Tab title="b" name="b">
        内容 2
      </Tab>
      <Tab title="c" name="c">
        内容 3
      </Tab>
      <Tab title="d" name="d">
        内容 4
      </Tab>
    </Tabs>
  )
}
```

**期望结果**

**实际结果**

**截图**
<img width="371" alt="image" src="https://github.com/AntmJS/vantui/assets/49827327/df23f661-0c1f-41bf-8659-99c66bd66244">

**环境**

**附加信息**

**Comment by json-q** [comment]
同问题，此 bug 不是每次都可以复现，但复现概率也不算小。
**使用场景：**
左侧列表，右侧表单，表单填写完调用 setActive 的方法切换至列表 tab。
**问题：**
虽然视图为列表，但是 tab 的选中项还是表单。

**Comment by GetWebHB** [comment]
还是比较严重的问题，场景比较多的
