### ISSUE TITLE
h5样式问题

### ISSUE THREAD

**Issue by Pinchuan** [AntmJS/vantui#602]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [*] Web 平台（H5）

**BUG 描述**
h5端表现和微信小程序呈现的样式不一样，h5端普遍字体和间距普遍放大
**复现步骤**

**期望结果**
期望和微信小程序一样的样式
**实际结果**

**截图**
![db0a0a5b962e79dc28ec81f2b4a63a6](https://github.com/AntmJS/vantui/assets/20009993/2e6f6e46-5dc2-4a7b-b0ae-a477901f2d71)

**环境**

**附加信息**

**Comment by zuolung** [comment]
查看下推荐的项目模板

**Comment by explorefit** [comment]
这个我遇到的一样的问题，按照项目模板设置后，页面样式变的很小
