### ISSUE TITLE
Field 设置 placeholder 颜色无效，placeholderClass、placeholderStyle、ConfigProvider设置 fieldPlaceholderTextColor 均无效

### ISSUE THREAD

**Issue by LMchensir** [AntmJS/vantui#607]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

Field 设置 placeholder 颜色无效，placeholderClass、placeholderStyle、ConfigProvider设置 fieldPlaceholderTextColor 均无效

设置 placeholder 的字体大小，背景颜色什么的属性都生效，唯独这个 placeholder 的字体颜色怎么设置都不生效

**复现步骤**
`const themeVars = {
    fieldPlaceholderTextColor: '#e19a9a',
    fieldInputTextColor: '#e19a9a',
  }`

` <View className="edit-business-card-content">
        <ConfigProvider themeVars={themeVars}>
          <CellGroup>
            <Field placeholderClass="edit-business-name-placeholder" placeholderStyle="color: #e19a9a" placeholder="请输入姓名" />
            <Field label="职位" placeholder="请输入职位" />
          </CellGroup>
        </ConfigProvider>
        <CellGroup>
          <Field label="手机号" placeholder="请输入手机号" />
          <Field label="企业名称" placeholder="请输入企业名称" />
        </CellGroup>
      </View>`

**期望结果**

**实际结果**

**截图**
![image](https://github.com/AntmJS/vantui/assets/51938074/6716b76f-e1d5-45d6-aef9-b0e63a2ba35a)
![image](https://github.com/AntmJS/vantui/assets/51938074/36b3397a-dab0-4e0a-9e8b-2e5d8a4e06bb)
![image](https://github.com/AntmJS/vantui/assets/51938074/3f931936-28d4-4bec-aed9-0300e4292aba)

**环境**

**附加信息**

**Comment by zuolung** [comment]
css变量导致placeholder-class解析错误
