### ISSUE TITLE
使用dialog/toast组件没有调用

### ISSUE THREAD

**Issue by nice-wwming** [AntmJS/vantui#626]
希望大佬们给看下是写法问题还是什么原因呢

**这个 Issue 涉及以下平台:**

- [X ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
<img width="607" alt="image" src="https://github.com/AntmJS/vantui/assets/53433576/85ddd7b4-b1cd-4373-8a4d-d017f654c761">

**环境**

**附加信息**

**Comment by zuolung** [comment]
漏掉了JSX

**Comment by cuiyajie** [comment]
@zuolung , 请问一下 这个回答是什么意思？是需要添加支持 JSX 的配置么？

**Comment by nice-wwming** [comment]
> [@zuolung](https://github.com/zuolung) , 请问一下 这个回答是什么意思？是需要添加支持 JSX 的配置么？

他这个函数不能直接调用,需要在下边加上jsx

![Image](https://github.com/user-attachments/assets/700d7257-860b-4bd0-ae48-4d63e4d54b57)
