### ISSUE TITLE
Table表格代码引起错误提示

### ISSUE THREAD

**Issue by zhouzyc** [AntmJS/vantui#631]
**这个 Issue 涉及以下平台:**

- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [X] Web 平台（H5）

**BUG 描述**
![image](https://github.com/AntmJS/vantui/assets/18420689/c0394957-8e8f-4c62-a4f6-9b09e3cb2bde)
以前上代码，如果在expandable=false的情况会引发错误
![image](https://github.com/AntmJS/vantui/assets/18420689/e3a75ed0-feae-4dca-92fc-9173532b47e8)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
[d82aff3f09324f5339d0bb50ca40e84b89f8d9ae]
