### ISSUE TITLE
Notify、Dialog、Toast组件，小程序端在页面跳转后返回，存在注册被覆盖的问题

### ISSUE THREAD

**Issue by caidesen** [AntmJS/vantui#635]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
<img width="237" alt="截屏2024-04-22 17 22 35" src="https://github.com/AntmJS/vantui/assets/42564090/3bd27ac6-2032-4707-9bf4-d0dd741c40d4">
推测是组件销毁时 off 操作未指定具体函数，导致上个页面中监听也失效了
**复现步骤**
现有两个页面，Page1 Page2，两个页面中都有使用组件<Notify id="xxx" />，id不同。
先由Page1 跳转至 Page2，随后返回至 Page1，Page1 中的所有Notify.show 没有反应
**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by zuolung** [comment]
之前的设计不严谨，使用useDidshow修复, 呼吁大家及时更新到3.3.6和2.5.13
