### ISSUE TITLE
WaterfallFlow 渲染瀑布流时未遵循数组循序

### ISSUE THREAD

**Issue by liuyongming1010** [AntmJS/vantui#655]
**这个 Issue 涉及以下平台:**

只在微信小程序平台使用发现，其他平台未测试，应该也有
- [ ✓] 微信小程序

**BUG 描述**
WaterfallFlow 渲染瀑布流时未遵循数组循序 

```
const dataSource = [
  {key:0},
  {key:1},
  {key:2},
  {key:3},
  {key:4},
  {key:6},
  {key:7},
  {key:8},
  {key:9},
]
<WaterfallFlow
     dataSource={dataSource}
     columnNum={2}
     gutter={[0,0]}
     calculationDelay={0}
     renderItem={(item, forceResize)=>{
           return  <View>
                        {item.key}
                </View>
    }}
 />
```

**实际结果**

```
columnNum={2}时：
输出结果为：
0，1
3，2
5，4
7，6
9，8

columnNum={3}时：
0，1，2
5，3，4
8，6，7
9


```
**截图**

![image](https://github.com/AntmJS/vantui/assets/24351661/9e81b9dd-7146-49ee-9b40-f3775da81e79)

**Comment by 751848178** [comment]
目前的实现逻辑是按照元素resize顺序来的，也就是说列表中3的图片比1优先加载完成，会先于1触发resize，这个时候3就会在1前面
同时按续排列的方式，极端情况下可能会导致瀑布流列高度相差较多的情况出现

**Comment by 751848178** [comment]
0,1加载完成时，首先站位左右两列的第一位，当2加载成功并且触发resize时，组件会取两列中高度最小的一列加入2，3加载完成时会再次找到两列中高度最小的一列加入，以此类推

**Comment by 751848178** [comment]
> > 0,1加载完成时，首先站位左右两列的极大，当2加载成功并且触发resize时，组件会取两列中高度最小的一列加入2，3加载完成时会再次找到两列中高度最小的一列加入，以此类推
> 
> 能否添加一个控制排序的参数

组件目前的实现是按需拼接，平衡每列的高度

- 列表项按照加载完成的顺序，依次拼接到当前高度最小的列中。

- 这种方式可以更好地平衡各列的高度，使得布局更均匀，但列表项的显示顺序可能与数据源中的顺序不同。

如果需要固定顺序的话，考虑下是否需要瀑布流组件？

**Comment by huahaichuan** [comment]
componentDidMount (): void {
    list.forEach((el, index) => {
      setTimeout(() => {
        this.data.push(el);
      }, 50 * index);
    });
  }
