### ISSUE TITLE
表单组件缺少name属性

### ISSUE THREAD

**Issue by xxyuze** [AntmJS/vantui#69]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

Field等组件没有name属性，无法在Form里面使用，原版的vant weapp是有的，是否是漏掉了？

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
我看了源码没有看到name属性的逻辑，是否只是文档写了，实际没有实现？你有真实测试过吗
