### ISSUE TITLE
Cascader 缓存问题。快速点击一级，二级会残留上次的。

### ISSUE THREAD

**Issue by debughao** [AntmJS/vantui#713]
**这个 Issue 涉及以下平台:**

- [x] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 头条小程序
- [ ] 快手小程序
- [ ] QQ 轻应用
- [ ] Web 平台（H5）

**BUG 描述**
Cascader 缓存问题。快速点击一级，二级会残留上次的。

**复现步骤**
快速点击一级，二级会残留上次的。
**期望结果**

**实际结果**

**截图**

https://github.com/user-attachments/assets/056f16d2-040a-4b1e-9022-9495712c7842

**环境**

**附加信息**

**Comment by debughao** [comment]
function PickAddress(){
    const [isVisiblevalue, setIsVisiblevalue] = useState(false)
    const [optionsvalue, setOptionsvalue] = useState([])
    const [value, setValue] = useState(['广东省', '广州市','白云区'])
    useEffect(()=>{
        api.areaListChildren({data:{parentId:-1}}).then((res)=>{
            setOptionsvalue(res.data)
        })
    },[])
    const lazyLoad = (node, resolve) => {
        console.log("node",node)
        if(node.id){
            api.areaListChildren({data:{parentId:node.id} ,filterCheck:true}).then((res)=>{
                resolve(res.data)
            })
        }else{
            resolve([])
        }

    }
    const change = (value) => {
        console.log("value",value)
        setValue(value)
    }
    return <>
        <Cell
            title="选择地址"
            value={value ? value.join('-') : '请选择地址'}
            onClick={() => {
                setIsVisiblevalue(true)
            }}
        ></Cell>
        <Cascader
            visible={isVisiblevalue}
            value={value}
            // @ts-ignore
            title="地址选择"
            textKey="areaName"
            valueKey="areaName"
            options={optionsvalue}
            onChange={change}
            closeable={true}
            lazy
            lazyLoad={lazyLoad}
            onClose={() => {
                setIsVisiblevalue(false)
            }}

        />
    </>

}

**Comment by zuolung** [comment]
交互问题

**Comment by HyaCiovo** [comment]
可以加个加载样式不让快速多次点击
