### ISSUE TITLE
Circle组件，在小程序中，属性中text不生效

### ISSUE THREAD

**Issue by shihongyu627** [AntmJS/vantui#72]
**BUG描述**
Circle组件，在小程序中，属性中text不生效

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/50938504/142404974-fb32d8bd-dff5-4a10-a7af-306b63b6ffba.png)
**环境**

**附加信息**

**Comment by Chitanda60** [comment]
@shihongyu627 未复现你说的场景，能否提供下完整的运行代码

**Comment by hisanshao** [comment]
真机和demo都是能正常展示的，你试下更新下开发者工具再试试？或者真机测一下

**Comment by Chitanda60** [comment]
如有出现可试下设置字体大小
