### ISSUE TITLE
按需引入包还是过大。

### ISSUE THREAD

**Issue by YC725968** [AntmJS/vantui#77]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
主包中未使用vantui，但是按需加载后，主包增加300k，好像按需引入不生效。

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
![image](https://user-images.githubusercontent.com/26359618/142999679-83aa9b51-1812-4fe7-9f95-b73bf403ba4e.png)已经生效了哦
