### ISSUE TITLE
安装后编译报错

### ISSUE THREAD

**Issue by YC725968** [AntmJS/vantui#78]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

![tarocuowu](https://user-images.githubusercontent.com/51156342/142726096-0971c377-ca6a-4d87-b33b-7762af170493.png)
**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by hisanshao** [comment]
是用户的Taro模版开发的吗

**Comment by YC725968** [comment]
是啊，就用taro，最新版的taro出现的

**Comment by hisanshao** [comment]
3.3.14全新的我拉下来添加@antmjs/vantui运行没有问题啊，你把代码放github上，链接发我吧。我这边复现不了

**Comment by hisanshao** [comment]
> 是啊，就用taro，最新版的taro出现的

3.3.14全新的我拉下来添加@antmjs/vantui运行没有问题啊，你把代码放github上，链接发我吧。我这边复现不了
