### ISSUE TITLE
datetime时间选择器，真机上特别卡，开发者工具上不卡

### ISSUE THREAD

**Issue by yeyu12** [AntmJS/vantui#80]
**BUG描述**
如标题

**复现步骤**
使用的是网站上的demo

**期望结果**
解决真机上的卡顿

**实际结果**

**截图**

**环境**
iphone 8p

**附加信息**

**Comment by yeyu12** [comment]
@Chitanda60 卡顿是稍微好点了，但还是卡。期待进一步优化

**Comment by hisanshao** [comment]
@yeyu12 手机品牌、型号报过来看看。他们自己手机上测说不卡顿

**Comment by hisanshao** [comment]
@yeyu12 卡顿问题修复了 1.2.7
