### ISSUE TITLE
Picker bug

### ISSUE THREAD

**Issue by hooliy** [AntmJS/vantui#83]
**BUG描述**
defaultIndex  设置默认值后，选项列无法滚动到小于 defaultIndex 值的列。
valueKey 设置后，组件使用时报错。

**复现步骤**

Taro 微信小程序项目中

**期望结果**

**实际结果**

**截图**

**环境**

**附加信息**

**Comment by Banlangenn** [comment]
https://github.com/AntmJS/vantui/issues/76

重复
