### ISSUE TITLE
Picker，多级联动，切换选项后，数据不展示

### ISSUE THREAD

**Issue by yeyu12** [AntmJS/vantui#99]
**BUG描述**
切换一级选项后，二级选项不展示数据，二级选项的数据量不一样。同时切换后，滑动二级现象有视觉卡顿

**复现步骤**

**期望结果**
数据展示

**实际结果**

**截图**

**环境**
微信开发者工具，ios微信真机测试

**附加信息**

**代码**
`
const customCycle= {
            天: [1],
            周: [1],
            月: [1],
            年: [1],
        }

for (let index = 2; index <= 300; index++) {
            customCycle['天'].push(index);

            if (index <= 5) {
                customCycle['周'].push(index);
                customCycle['年'].push(index);
            }
            if (index <= 12) {
                customCycle['月'].push(index);
            }
        }

const columns  = []
columns.push({
            values: Object.keys(customCycle),
            className: 'column1',
            defaultIndex: 1
        })
        columns.push({
            values: customCycle['周'],
            className: 'column2',
            defaultIndex: 1
        })

function onChange (event) => {
        const {
            picker,
            value,
            index
        } = event.detail;
        console.log(event.detail)
        picker.setColumnValues(1, this.state.customCycle[value[0]]);
    }

<Picker
                                    columns={this.state.columns}
                                    onChange={this.onChange}
                                    showToolbar={false}
                                />
`

**Comment by zuolung** [comment]
vantui的版本是多少
